
// fix ubiquitous warning C5204: 'boost::blah::blah<Blah>': class has virtual functions, but its trivial destructor is not virtual; instances of objects derived from this class may not be destructed correctly
//
// while this generally CAN/MAY be an issue, we brutally assume that the Boost Boys know their shit and NEVER make this mistake, i.e. the classes/structs in question are *implicitly `final`*!
// To play it kinda safe, we apply this 'please shut up' fix to this dummy=see-if-we-can-compile-Ev'ryTing source file only:

#if defined(_MSC_VER)
#pragma warning(disable: 5204)

// fix/shut up warning C4266: 'void boost::blah::blah::blah(...)': no override available for virtual member function from base 'boost::blah::blah'; function is hidden
#pragma warning(disable: 4266)
#endif

#include <boost/fusion/adapted.hpp>
#include <boost/fusion/adapted/adt.hpp>
#include <boost/fusion/adapted/adt/adapt_adt.hpp>
#include <boost/fusion/adapted/adt/adapt_adt_named.hpp>
#include <boost/fusion/adapted/adt/adapt_assoc_adt.hpp>
#include <boost/fusion/adapted/adt/adapt_assoc_adt_named.hpp>
#include <boost/fusion/adapted/array.hpp>
#include <boost/fusion/adapted/array/at_impl.hpp>
#include <boost/fusion/adapted/array/begin_impl.hpp>
#include <boost/fusion/adapted/array/category_of_impl.hpp>
#include <boost/fusion/adapted/array/deref_impl.hpp>
#include <boost/fusion/adapted/array/end_impl.hpp>
#include <boost/fusion/adapted/array/is_sequence_impl.hpp>
#include <boost/fusion/adapted/array/is_view_impl.hpp>
#include <boost/fusion/adapted/array/size_impl.hpp>
#include <boost/fusion/adapted/array/tag_of.hpp>
#include <boost/fusion/adapted/array/value_at_impl.hpp>
#include <boost/fusion/adapted/array/value_of_impl.hpp>
#include <boost/fusion/adapted/boost_array.hpp>
#include <boost/fusion/adapted/boost_array/array_iterator.hpp>
#include <boost/fusion/adapted/boost_array/tag_of.hpp>
#include <boost/fusion/adapted/boost_tuple.hpp>
#include <boost/fusion/adapted/boost_tuple/boost_tuple_iterator.hpp>
#include <boost/fusion/adapted/boost_tuple/mpl/clear.hpp>
#include <boost/fusion/adapted/boost_tuple/tag_of.hpp>
#include <boost/fusion/adapted/mpl.hpp>
#include <boost/fusion/adapted/mpl/mpl_iterator.hpp>
#include <boost/fusion/adapted/std_array.hpp>
#include <boost/fusion/adapted/std_array/std_array_iterator.hpp>
#include <boost/fusion/adapted/std_array/tag_of.hpp>
#include <boost/fusion/adapted/std_pair.hpp>
#include <boost/fusion/adapted/std_tuple.hpp>
#include <boost/fusion/adapted/std_tuple/mpl/clear.hpp>
#include <boost/fusion/adapted/std_tuple/std_tuple_iterator.hpp>
#include <boost/fusion/adapted/std_tuple/tag_of.hpp>
#include <boost/fusion/adapted/struct.hpp>
#include <boost/fusion/adapted/struct/adapt_assoc_struct.hpp>
#include <boost/fusion/adapted/struct/adapt_assoc_struct_named.hpp>
#include <boost/fusion/adapted/struct/adapt_struct.hpp>
#include <boost/fusion/adapted/struct/adapt_struct_named.hpp>
#include <boost/fusion/adapted/struct/define_assoc_struct.hpp>
#include <boost/fusion/adapted/struct/define_struct.hpp>
#include <boost/fusion/adapted/struct/define_struct_inline.hpp>
#include <boost/fusion/algorithm.hpp>
#include <boost/fusion/algorithm/auxiliary.hpp>
#include <boost/fusion/algorithm/auxiliary/copy.hpp>
#include <boost/fusion/algorithm/auxiliary/move.hpp>
#include <boost/fusion/algorithm/iteration.hpp>
#include <boost/fusion/algorithm/iteration/accumulate.hpp>
#include <boost/fusion/algorithm/iteration/accumulate_fwd.hpp>
#include <boost/fusion/algorithm/iteration/fold.hpp>
#include <boost/fusion/algorithm/iteration/fold_fwd.hpp>
#include <boost/fusion/algorithm/iteration/for_each.hpp>
#include <boost/fusion/algorithm/iteration/for_each_fwd.hpp>
#include <boost/fusion/algorithm/iteration/iter_fold.hpp>
#include <boost/fusion/algorithm/iteration/iter_fold_fwd.hpp>
#include <boost/fusion/algorithm/iteration/reverse_fold.hpp>
#include <boost/fusion/algorithm/iteration/reverse_fold_fwd.hpp>
#include <boost/fusion/algorithm/iteration/reverse_iter_fold.hpp>
#include <boost/fusion/algorithm/iteration/reverse_iter_fold_fwd.hpp>
#include <boost/fusion/algorithm/query.hpp>
#include <boost/fusion/algorithm/query/all.hpp>
#include <boost/fusion/algorithm/query/any.hpp>
#include <boost/fusion/algorithm/query/count.hpp>
#include <boost/fusion/algorithm/query/count_if.hpp>
#include <boost/fusion/algorithm/query/find.hpp>
#include <boost/fusion/algorithm/query/find_fwd.hpp>
#include <boost/fusion/algorithm/query/find_if.hpp>
#include <boost/fusion/algorithm/query/find_if_fwd.hpp>
#include <boost/fusion/algorithm/query/none.hpp>
#include <boost/fusion/algorithm/transformation.hpp>
#include <boost/fusion/algorithm/transformation/clear.hpp>
#include <boost/fusion/algorithm/transformation/erase.hpp>
#include <boost/fusion/algorithm/transformation/erase_key.hpp>
#include <boost/fusion/algorithm/transformation/filter.hpp>
#include <boost/fusion/algorithm/transformation/filter_if.hpp>
#include <boost/fusion/algorithm/transformation/flatten.hpp>
#include <boost/fusion/algorithm/transformation/insert.hpp>
#include <boost/fusion/algorithm/transformation/insert_range.hpp>
#include <boost/fusion/algorithm/transformation/join.hpp>
#include <boost/fusion/algorithm/transformation/pop_back.hpp>
#include <boost/fusion/algorithm/transformation/pop_front.hpp>
#include <boost/fusion/algorithm/transformation/push_back.hpp>
#include <boost/fusion/algorithm/transformation/push_front.hpp>
#include <boost/fusion/algorithm/transformation/remove.hpp>
#include <boost/fusion/algorithm/transformation/remove_if.hpp>
#include <boost/fusion/algorithm/transformation/replace.hpp>
#include <boost/fusion/algorithm/transformation/replace_if.hpp>
#include <boost/fusion/algorithm/transformation/reverse.hpp>
#include <boost/fusion/algorithm/transformation/transform.hpp>
#include <boost/fusion/algorithm/transformation/zip.hpp>
#include <boost/fusion/container.hpp>
#include <boost/fusion/container/deque.hpp>
#include <boost/fusion/container/deque/back_extended_deque.hpp>
#include <boost/fusion/container/deque/convert.hpp>
#include <boost/fusion/container/deque/deque.hpp>
#include <boost/fusion/container/deque/deque_fwd.hpp>
#include <boost/fusion/container/deque/deque_iterator.hpp>
#include <boost/fusion/container/deque/front_extended_deque.hpp>
#include <boost/fusion/container/generation.hpp>
#include <boost/fusion/container/generation/cons_tie.hpp>
#include <boost/fusion/container/generation/deque_tie.hpp>
#include <boost/fusion/container/generation/ignore.hpp>
#include <boost/fusion/container/generation/list_tie.hpp>
#include <boost/fusion/container/generation/make_cons.hpp>
#include <boost/fusion/container/generation/make_deque.hpp>
#include <boost/fusion/container/generation/make_list.hpp>
#include <boost/fusion/container/generation/make_map.hpp>
#include <boost/fusion/container/generation/make_set.hpp>
#include <boost/fusion/container/generation/make_vector.hpp>
#include <boost/fusion/container/generation/map_tie.hpp>
#include <boost/fusion/container/generation/pair_tie.hpp>
#include <boost/fusion/container/generation/vector_tie.hpp>
#include <boost/fusion/container/list.hpp>
#include <boost/fusion/container/list/cons.hpp>
#include <boost/fusion/container/list/cons_fwd.hpp>
#include <boost/fusion/container/list/cons_iterator.hpp>
#include <boost/fusion/container/list/convert.hpp>
#include <boost/fusion/container/list/list.hpp>
#include <boost/fusion/container/list/list_fwd.hpp>
#include <boost/fusion/container/list/nil.hpp>
#include <boost/fusion/container/map.hpp>
#include <boost/fusion/container/map/convert.hpp>
#include <boost/fusion/container/map/map.hpp>
#include <boost/fusion/container/map/map_fwd.hpp>
#include <boost/fusion/container/map/map_iterator.hpp>
#include <boost/fusion/container/set.hpp>
#include <boost/fusion/container/set/convert.hpp>
#include <boost/fusion/container/set/set.hpp>
#include <boost/fusion/container/set/set_fwd.hpp>
#include <boost/fusion/container/vector.hpp>
#include <boost/fusion/container/vector/convert.hpp>
#include <boost/fusion/container/vector/vector.hpp>
#include <boost/fusion/container/vector/vector10.hpp>
#include <boost/fusion/container/vector/vector20.hpp>
#include <boost/fusion/container/vector/vector30.hpp>
#include <boost/fusion/container/vector/vector40.hpp>
#include <boost/fusion/container/vector/vector50.hpp>
#include <boost/fusion/container/vector/vector_fwd.hpp>
#include <boost/fusion/container/vector/vector_iterator.hpp>
#include <boost/fusion/functional.hpp>
#include <boost/fusion/functional/adapter.hpp>
#include <boost/fusion/functional/adapter/fused.hpp>
#include <boost/fusion/functional/adapter/fused_function_object.hpp>
#include <boost/fusion/functional/adapter/fused_procedure.hpp>
#include <boost/fusion/functional/adapter/limits.hpp>
#include <boost/fusion/functional/adapter/unfused.hpp>
#include <boost/fusion/functional/adapter/unfused_typed.hpp>
#include <boost/fusion/functional/generation.hpp>
#include <boost/fusion/functional/generation/make_fused.hpp>
#include <boost/fusion/functional/generation/make_fused_function_object.hpp>
#include <boost/fusion/functional/generation/make_fused_procedure.hpp>
#include <boost/fusion/functional/generation/make_unfused.hpp>
#include <boost/fusion/functional/invocation.hpp>
#include <boost/fusion/functional/invocation/invoke.hpp>
#include <boost/fusion/functional/invocation/invoke_function_object.hpp>
#include <boost/fusion/functional/invocation/invoke_procedure.hpp>
#include <boost/fusion/functional/invocation/limits.hpp>
#include <boost/fusion/include/accumulate.hpp>
#include <boost/fusion/include/adapt_adt.hpp>
#include <boost/fusion/include/adapt_adt_named.hpp>
#include <boost/fusion/include/adapt_assoc_adt.hpp>
#include <boost/fusion/include/adapt_assoc_adt_named.hpp>
#include <boost/fusion/include/adapt_assoc_struct.hpp>
#include <boost/fusion/include/adapt_assoc_struct_named.hpp>
#include <boost/fusion/include/adapt_struct.hpp>
#include <boost/fusion/include/adapt_struct_named.hpp>
#include <boost/fusion/include/adapted.hpp>
#include <boost/fusion/include/adapter.hpp>
#include <boost/fusion/include/advance.hpp>
#include <boost/fusion/include/algorithm.hpp>
#include <boost/fusion/include/all.hpp>
#include <boost/fusion/include/any.hpp>
#include <boost/fusion/include/array.hpp>
#include <boost/fusion/include/as_deque.hpp>
#include <boost/fusion/include/as_list.hpp>
#include <boost/fusion/include/as_map.hpp>
#include <boost/fusion/include/as_set.hpp>
#include <boost/fusion/include/as_vector.hpp>
#include <boost/fusion/include/at.hpp>
#include <boost/fusion/include/at_c.hpp>
#include <boost/fusion/include/at_key.hpp>
#include <boost/fusion/include/auxiliary.hpp>
#include <boost/fusion/include/back.hpp>
#include <boost/fusion/include/begin.hpp>
#include <boost/fusion/include/boost_array.hpp>
#include <boost/fusion/include/boost_tuple.hpp>
#include <boost/fusion/include/category_of.hpp>
#include <boost/fusion/include/clear.hpp>
#include <boost/fusion/include/comparison.hpp>
#include <boost/fusion/include/cons.hpp>
#include <boost/fusion/include/cons_tie.hpp>
#include <boost/fusion/include/container.hpp>
#include <boost/fusion/include/convert.hpp>
#include <boost/fusion/include/copy.hpp>
#include <boost/fusion/include/count.hpp>
#include <boost/fusion/include/count_if.hpp>
#include <boost/fusion/include/deduce.hpp>
#include <boost/fusion/include/deduce_sequence.hpp>
#include <boost/fusion/include/define_assoc_struct.hpp>
#include <boost/fusion/include/define_struct.hpp>
#include <boost/fusion/include/define_struct_inline.hpp>
#include <boost/fusion/include/deque.hpp>
#include <boost/fusion/include/deque_fwd.hpp>
#include <boost/fusion/include/deque_tie.hpp>
#include <boost/fusion/include/deref.hpp>
#include <boost/fusion/include/deref_data.hpp>
#include <boost/fusion/include/distance.hpp>
#include <boost/fusion/include/empty.hpp>
#include <boost/fusion/include/end.hpp>
#include <boost/fusion/include/equal_to.hpp>
#include <boost/fusion/include/erase.hpp>
#include <boost/fusion/include/erase_key.hpp>
#include <boost/fusion/include/filter.hpp>
#include <boost/fusion/include/filter_if.hpp>
#include <boost/fusion/include/filter_view.hpp>
#include <boost/fusion/include/find.hpp>
#include <boost/fusion/include/find_if.hpp>
#include <boost/fusion/include/flatten.hpp>
#include <boost/fusion/include/flatten_view.hpp>
#include <boost/fusion/include/fold.hpp>
#include <boost/fusion/include/for_each.hpp>
#include <boost/fusion/include/front.hpp>
#include <boost/fusion/include/functional.hpp>
#include <boost/fusion/include/fused.hpp>
#include <boost/fusion/include/fused_function_object.hpp>
#include <boost/fusion/include/fused_procedure.hpp>
#include <boost/fusion/include/generation.hpp>
#include <boost/fusion/include/greater.hpp>
#include <boost/fusion/include/greater_equal.hpp>
#include <boost/fusion/include/has_key.hpp>
#include <boost/fusion/include/hash.hpp>
#include <boost/fusion/include/identity_view.hpp>
#include <boost/fusion/include/ignore.hpp>
#include <boost/fusion/include/in.hpp>
#include <boost/fusion/include/insert.hpp>
#include <boost/fusion/include/insert_range.hpp>
#include <boost/fusion/include/intrinsic.hpp>
#include <boost/fusion/include/invocation.hpp>
#include <boost/fusion/include/invoke.hpp>
#include <boost/fusion/include/invoke_function_object.hpp>
#include <boost/fusion/include/invoke_procedure.hpp>
#include <boost/fusion/include/io.hpp>
#include <boost/fusion/include/is_iterator.hpp>
#include <boost/fusion/include/is_segmented.hpp>
#include <boost/fusion/include/is_sequence.hpp>
#include <boost/fusion/include/is_view.hpp>
#include <boost/fusion/include/iter_fold.hpp>
#include <boost/fusion/include/iteration.hpp>
#include <boost/fusion/include/iterator.hpp>
#include <boost/fusion/include/iterator_adapter.hpp>
#include <boost/fusion/include/iterator_base.hpp>
#include <boost/fusion/include/iterator_facade.hpp>
#include <boost/fusion/include/iterator_range.hpp>
#include <boost/fusion/include/join.hpp>
#include <boost/fusion/include/joint_view.hpp>
#include <boost/fusion/include/key_of.hpp>
#include <boost/fusion/include/less.hpp>
#include <boost/fusion/include/less_equal.hpp>
#include <boost/fusion/include/list.hpp>
#include <boost/fusion/include/list_fwd.hpp>
#include <boost/fusion/include/list_tie.hpp>
#include <boost/fusion/include/make_cons.hpp>
#include <boost/fusion/include/make_deque.hpp>
#include <boost/fusion/include/make_fused.hpp>
#include <boost/fusion/include/make_fused_function_object.hpp>
#include <boost/fusion/include/make_fused_procedure.hpp>
#include <boost/fusion/include/make_list.hpp>
#include <boost/fusion/include/make_map.hpp>
#include <boost/fusion/include/make_set.hpp>
#include <boost/fusion/include/make_tuple.hpp>
#include <boost/fusion/include/make_unfused.hpp>
#include <boost/fusion/include/make_vector.hpp>
#include <boost/fusion/include/map.hpp>
#include <boost/fusion/include/map_fwd.hpp>
#include <boost/fusion/include/map_tie.hpp>
#include <boost/fusion/include/move.hpp>
#include <boost/fusion/include/mpl.hpp>
#include <boost/fusion/include/next.hpp>
#include <boost/fusion/include/nil.hpp>
#include <boost/fusion/include/none.hpp>
#include <boost/fusion/include/not_equal_to.hpp>
#include <boost/fusion/include/nview.hpp>
#include <boost/fusion/include/out.hpp>
#include <boost/fusion/include/pair.hpp>
#include <boost/fusion/include/pair_tie.hpp>
#include <boost/fusion/include/pop_back.hpp>
#include <boost/fusion/include/pop_front.hpp>
#include <boost/fusion/include/prior.hpp>
#include <boost/fusion/include/proxy_type.hpp>
#include <boost/fusion/include/push_back.hpp>
#include <boost/fusion/include/push_front.hpp>
#include <boost/fusion/include/query.hpp>
#include <boost/fusion/include/remove.hpp>
#include <boost/fusion/include/remove_if.hpp>
#include <boost/fusion/include/repetitive_view.hpp>
#include <boost/fusion/include/replace.hpp>
#include <boost/fusion/include/replace_if.hpp>
#include <boost/fusion/include/reverse.hpp>
#include <boost/fusion/include/reverse_fold.hpp>
#include <boost/fusion/include/reverse_iter_fold.hpp>
#include <boost/fusion/include/reverse_view.hpp>
#include <boost/fusion/include/segmented_fold_until.hpp>
#include <boost/fusion/include/segmented_iterator.hpp>
#include <boost/fusion/include/segments.hpp>
#include <boost/fusion/include/sequence.hpp>
#include <boost/fusion/include/sequence_base.hpp>
#include <boost/fusion/include/sequence_facade.hpp>
#include <boost/fusion/include/set.hpp>
#include <boost/fusion/include/set_fwd.hpp>
#include <boost/fusion/include/single_view.hpp>
#include <boost/fusion/include/size.hpp>
#include <boost/fusion/include/std_array.hpp>
#include <boost/fusion/include/std_pair.hpp>
#include <boost/fusion/include/std_tuple.hpp>
#include <boost/fusion/include/struct.hpp>
#include <boost/fusion/include/support.hpp>
#include <boost/fusion/include/swap.hpp>
#include <boost/fusion/include/tag_of.hpp>
#include <boost/fusion/include/tag_of_fwd.hpp>
#include <boost/fusion/include/transform.hpp>
#include <boost/fusion/include/transform_view.hpp>
#include <boost/fusion/include/transformation.hpp>
#include <boost/fusion/include/tuple.hpp>
#include <boost/fusion/include/tuple_fwd.hpp>
#include <boost/fusion/include/tuple_tie.hpp>
#include <boost/fusion/include/unfused.hpp>
#include <boost/fusion/include/unfused_typed.hpp>
#include <boost/fusion/include/unused.hpp>
#include <boost/fusion/include/value_at.hpp>
#include <boost/fusion/include/value_at_key.hpp>
#include <boost/fusion/include/value_of.hpp>
#include <boost/fusion/include/value_of_data.hpp>
#include <boost/fusion/include/vector.hpp>
#include <boost/fusion/include/vector10.hpp>
#include <boost/fusion/include/vector20.hpp>
#include <boost/fusion/include/vector30.hpp>
#include <boost/fusion/include/vector40.hpp>
#include <boost/fusion/include/vector50.hpp>
#include <boost/fusion/include/vector_fwd.hpp>
#include <boost/fusion/include/vector_tie.hpp>
#include <boost/fusion/include/view.hpp>
#include <boost/fusion/include/void.hpp>
#include <boost/fusion/include/zip.hpp>
#include <boost/fusion/include/zip_view.hpp>
#include <boost/fusion/iterator.hpp>
#include <boost/fusion/iterator/advance.hpp>
#include <boost/fusion/iterator/basic_iterator.hpp>
#include <boost/fusion/iterator/deref.hpp>
#include <boost/fusion/iterator/deref_data.hpp>
#include <boost/fusion/iterator/distance.hpp>
#include <boost/fusion/iterator/equal_to.hpp>
#include <boost/fusion/iterator/iterator_adapter.hpp>
#include <boost/fusion/iterator/iterator_facade.hpp>
#include <boost/fusion/iterator/key_of.hpp>
#include <boost/fusion/iterator/mpl.hpp>
#include <boost/fusion/iterator/mpl/convert_iterator.hpp>
#include <boost/fusion/iterator/mpl/fusion_iterator.hpp>
#include <boost/fusion/iterator/next.hpp>
#include <boost/fusion/iterator/prior.hpp>
#include <boost/fusion/iterator/segmented_iterator.hpp>
#include <boost/fusion/iterator/value_of.hpp>
#include <boost/fusion/iterator/value_of_data.hpp>
#include <boost/fusion/mpl.hpp>
#include <boost/fusion/mpl/at.hpp>
#include <boost/fusion/mpl/back.hpp>
#include <boost/fusion/mpl/begin.hpp>
#include <boost/fusion/mpl/clear.hpp>
#include <boost/fusion/mpl/empty.hpp>
#include <boost/fusion/mpl/end.hpp>
#include <boost/fusion/mpl/erase.hpp>
#include <boost/fusion/mpl/erase_key.hpp>
#include <boost/fusion/mpl/front.hpp>
#include <boost/fusion/mpl/has_key.hpp>
#include <boost/fusion/mpl/insert.hpp>
#include <boost/fusion/mpl/insert_range.hpp>
#include <boost/fusion/mpl/pop_back.hpp>
#include <boost/fusion/mpl/pop_front.hpp>
#include <boost/fusion/mpl/push_back.hpp>
#include <boost/fusion/mpl/push_front.hpp>
#include <boost/fusion/mpl/size.hpp>
#include <boost/fusion/sequence.hpp>
#include <boost/fusion/sequence/comparison.hpp>
#include <boost/fusion/sequence/comparison/enable_comparison.hpp>
#include <boost/fusion/sequence/comparison/equal_to.hpp>
#include <boost/fusion/sequence/comparison/greater.hpp>
#include <boost/fusion/sequence/comparison/greater_equal.hpp>
#include <boost/fusion/sequence/comparison/less.hpp>
#include <boost/fusion/sequence/comparison/less_equal.hpp>
#include <boost/fusion/sequence/comparison/not_equal_to.hpp>
#include <boost/fusion/sequence/convert.hpp>
#include <boost/fusion/sequence/hash.hpp>
#include <boost/fusion/sequence/intrinsic.hpp>
#include <boost/fusion/sequence/intrinsic/at.hpp>
#include <boost/fusion/sequence/intrinsic/at_c.hpp>
#include <boost/fusion/sequence/intrinsic/at_key.hpp>
#include <boost/fusion/sequence/intrinsic/back.hpp>
#include <boost/fusion/sequence/intrinsic/begin.hpp>
#include <boost/fusion/sequence/intrinsic/empty.hpp>
#include <boost/fusion/sequence/intrinsic/end.hpp>
#include <boost/fusion/sequence/intrinsic/front.hpp>
#include <boost/fusion/sequence/intrinsic/has_key.hpp>
#include <boost/fusion/sequence/intrinsic/segments.hpp>
#include <boost/fusion/sequence/intrinsic/size.hpp>
#include <boost/fusion/sequence/intrinsic/swap.hpp>
#include <boost/fusion/sequence/intrinsic/value_at.hpp>
#include <boost/fusion/sequence/intrinsic/value_at_key.hpp>
#include <boost/fusion/sequence/intrinsic_fwd.hpp>
#include <boost/fusion/sequence/io.hpp>
#include <boost/fusion/sequence/io/in.hpp>
#include <boost/fusion/sequence/io/out.hpp>
#include <boost/fusion/sequence/sequence_facade.hpp>
#include <boost/fusion/support.hpp>
#include <boost/fusion/tuple.hpp>
#include <boost/fusion/tuple/make_tuple.hpp>
#include <boost/fusion/tuple/tuple.hpp>
#include <boost/fusion/tuple/tuple_fwd.hpp>
#include <boost/fusion/tuple/tuple_tie.hpp>
#include <boost/fusion/view.hpp>
#include <boost/fusion/view/filter_view.hpp>
#include <boost/fusion/view/filter_view/filter_view.hpp>
#include <boost/fusion/view/filter_view/filter_view_iterator.hpp>
#include <boost/fusion/view/flatten_view.hpp>
#include <boost/fusion/view/flatten_view/flatten_view.hpp>
#include <boost/fusion/view/flatten_view/flatten_view_iterator.hpp>
#include <boost/fusion/view/identity_view.hpp>
#include <boost/fusion/view/identity_view/identity_view.hpp>
#include <boost/fusion/view/iterator_range.hpp>
#include <boost/fusion/view/iterator_range/iterator_range.hpp>
#include <boost/fusion/view/joint_view.hpp>
#include <boost/fusion/view/joint_view/joint_view.hpp>
#include <boost/fusion/view/joint_view/joint_view_fwd.hpp>
#include <boost/fusion/view/joint_view/joint_view_iterator.hpp>
#include <boost/fusion/view/nview.hpp>
#include <boost/fusion/view/nview/nview.hpp>
#include <boost/fusion/view/nview/nview_iterator.hpp>
#include <boost/fusion/view/repetitive_view.hpp>
#include <boost/fusion/view/repetitive_view/repetitive_view.hpp>
#include <boost/fusion/view/repetitive_view/repetitive_view_fwd.hpp>
#include <boost/fusion/view/repetitive_view/repetitive_view_iterator.hpp>
#include <boost/fusion/view/reverse_view.hpp>
#include <boost/fusion/view/reverse_view/reverse_view.hpp>
#include <boost/fusion/view/reverse_view/reverse_view_iterator.hpp>
#include <boost/fusion/view/single_view.hpp>
#include <boost/fusion/view/single_view/single_view.hpp>
#include <boost/fusion/view/single_view/single_view_iterator.hpp>
#include <boost/fusion/view/transform_view.hpp>
#include <boost/fusion/view/transform_view/transform_view.hpp>
#include <boost/fusion/view/transform_view/transform_view_fwd.hpp>
#include <boost/fusion/view/transform_view/transform_view_iterator.hpp>
#include <boost/fusion/view/zip_view.hpp>
#include <boost/fusion/view/zip_view/zip_view.hpp>
#include <boost/fusion/view/zip_view/zip_view_iterator.hpp>
#include <boost/fusion/view/zip_view/zip_view_iterator_fwd.hpp>

