
#include <boost/outcome.hpp>
#include <boost/outcome/bad_access.hpp>
#include <boost/outcome/basic_outcome.hpp>
#include <boost/outcome/basic_result.hpp>
#include <boost/outcome/boost_outcome.hpp>
#include <boost/outcome/boost_result.hpp>
#include <boost/outcome/config.hpp>
#include <boost/outcome/convert.hpp>
#include <boost/outcome/coroutine_support.hpp>
#include <boost/outcome/detail/basic_outcome_exception_observers.hpp>
#include <boost/outcome/detail/basic_outcome_exception_observers_impl.hpp>
#include <boost/outcome/detail/basic_outcome_failure_observers.hpp>
#include <boost/outcome/detail/basic_result_error_observers.hpp>
#include <boost/outcome/detail/basic_result_final.hpp>
#include <boost/outcome/detail/basic_result_storage.hpp>
#include <boost/outcome/detail/basic_result_value_observers.hpp>
#include <boost/outcome/detail/revision.hpp>
#include <boost/outcome/detail/trait_std_error_code.hpp>
#include <boost/outcome/detail/trait_std_exception.hpp>
#include <boost/outcome/detail/try.h>
#include <boost/outcome/detail/value_storage.hpp>
#include <boost/outcome/detail/version.hpp>
#include <boost/outcome/experimental/coroutine_support.hpp>
#include <boost/outcome/experimental/result.h>
#include <boost/outcome/experimental/status-code/boost_error_code.hpp>
#include <boost/outcome/experimental/status-code/com_code.hpp>
#include <boost/outcome/experimental/status-code/config.hpp>
#include <boost/outcome/experimental/status-code/error.hpp>
#include <boost/outcome/experimental/status-code/errored_status_code.hpp>
#include <boost/outcome/experimental/status-code/generic_code.hpp>
#include <boost/outcome/experimental/status-code/getaddrinfo_code.hpp>
#include <boost/outcome/experimental/status-code/http_status_code.hpp>
#include <boost/outcome/experimental/status-code/iostream_support.hpp>
#include <boost/outcome/experimental/status-code/nested_status_code.hpp>
#include <boost/outcome/experimental/status-code/nt_code.hpp>
#include <boost/outcome/experimental/status-code/posix_code.hpp>
#include <boost/outcome/experimental/status-code/quick_status_code_from_enum.hpp>
#include <boost/outcome/experimental/status-code/result.hpp>
#include <boost/outcome/experimental/status-code/status_code.hpp>
#include <boost/outcome/experimental/status-code/status_code_domain.hpp>
#include <boost/outcome/experimental/status-code/status_error.hpp>
#include <boost/outcome/experimental/status-code/std_error_code.hpp>
#include <boost/outcome/experimental/status-code/system_code.hpp>
#include <boost/outcome/experimental/status-code/system_code_from_exception.hpp>
#include <boost/outcome/experimental/status-code/system_error2.hpp>
#include <boost/outcome/experimental/status-code/win32_code.hpp>
#include <boost/outcome/experimental/status_outcome.hpp>
#include <boost/outcome/experimental/status_result.hpp>
#include <boost/outcome/iostream_support.hpp>
#include <boost/outcome/outcome.hpp>
#include <boost/outcome/outcome_gdb.h>
#include <boost/outcome/policy/all_narrow.hpp>
#include <boost/outcome/policy/base.hpp>
#include <boost/outcome/policy/fail_to_compile_observers.hpp>
#include <boost/outcome/policy/outcome_error_code_throw_as_system_error.hpp>
#include <boost/outcome/policy/outcome_exception_ptr_rethrow.hpp>
#include <boost/outcome/policy/result_error_code_throw_as_system_error.hpp>
#include <boost/outcome/policy/result_exception_ptr_rethrow.hpp>
#include <boost/outcome/policy/terminate.hpp>
#include <boost/outcome/policy/throw_bad_result_access.hpp>
#include <boost/outcome/result.hpp>
#include <boost/outcome/std_outcome.hpp>
#include <boost/outcome/std_result.hpp>
#include <boost/outcome/success_failure.hpp>
#include <boost/outcome/trait.hpp>
#include <boost/outcome/try.hpp>
#include <boost/outcome/utils.hpp>

