
#include <boost/signals2.hpp>
#include <boost/signals2/connection.hpp>
#include <boost/signals2/deconstruct.hpp>
#include <boost/signals2/deconstruct_ptr.hpp>
#include <boost/signals2/detail/auto_buffer.hpp>
#include <boost/signals2/detail/foreign_ptr.hpp>
#include <boost/signals2/detail/lwm_nop.hpp>
#include <boost/signals2/detail/lwm_pthreads.hpp>
#include <boost/signals2/detail/lwm_win32_cs.hpp>
#include <boost/signals2/detail/null_output_iterator.hpp>
#include <boost/signals2/detail/preprocessed_arg_type.hpp>
#include <boost/signals2/detail/preprocessed_arg_type_template.hpp>
#include <boost/signals2/detail/replace_slot_function.hpp>
#include <boost/signals2/detail/result_type_wrapper.hpp>
#include <boost/signals2/detail/scope_guard.hpp>
#include <boost/signals2/detail/signal_template.hpp>
#include <boost/signals2/detail/signals_common.hpp>
#include <boost/signals2/detail/signals_common_macros.hpp>
#include <boost/signals2/detail/slot_call_iterator.hpp>
#include <boost/signals2/detail/slot_groups.hpp>
#include <boost/signals2/detail/slot_template.hpp>
#include <boost/signals2/detail/tracked_objects_visitor.hpp>
#include <boost/signals2/detail/unique_lock.hpp>
#include <boost/signals2/detail/variadic_arg_type.hpp>
#include <boost/signals2/detail/variadic_slot_invoker.hpp>
#include <boost/signals2/dummy_mutex.hpp>
#include <boost/signals2/expired_slot.hpp>
#include <boost/signals2/last_value.hpp>
#include <boost/signals2/mutex.hpp>
#include <boost/signals2/optional_last_value.hpp>
#include <boost/signals2/postconstructible.hpp>
#include <boost/signals2/predestructible.hpp>
#include <boost/signals2/preprocessed_signal.hpp>
#include <boost/signals2/preprocessed_slot.hpp>
#include <boost/signals2/shared_connection_block.hpp>
#include <boost/signals2/signal.hpp>
#include <boost/signals2/signal_base.hpp>
#include <boost/signals2/signal_type.hpp>
#include <boost/signals2/slot.hpp>
#include <boost/signals2/slot_base.hpp>
#include <boost/signals2/trackable.hpp>
#include <boost/signals2/variadic_signal.hpp>
#include <boost/signals2/variadic_slot.hpp>

