
#include <boost/preprocessor.hpp>
#include <boost/preprocessor/arithmetic.hpp>
#include <boost/preprocessor/arithmetic/add.hpp>
#include <boost/preprocessor/arithmetic/dec.hpp>
#include <boost/preprocessor/arithmetic/detail/div_base.hpp>
#include <boost/preprocessor/arithmetic/detail/is_1_number.hpp>
#include <boost/preprocessor/arithmetic/detail/is_maximum_number.hpp>
#include <boost/preprocessor/arithmetic/detail/is_minimum_number.hpp>
#include <boost/preprocessor/arithmetic/detail/maximum_number.hpp>
#include <boost/preprocessor/arithmetic/div.hpp>
#include <boost/preprocessor/arithmetic/inc.hpp>
#include <boost/preprocessor/arithmetic/limits/dec_1024.hpp>
#include <boost/preprocessor/arithmetic/limits/dec_256.hpp>
#include <boost/preprocessor/arithmetic/limits/dec_512.hpp>
#include <boost/preprocessor/arithmetic/limits/inc_1024.hpp>
#include <boost/preprocessor/arithmetic/limits/inc_256.hpp>
#include <boost/preprocessor/arithmetic/limits/inc_512.hpp>
#include <boost/preprocessor/arithmetic/mod.hpp>
#include <boost/preprocessor/arithmetic/mul.hpp>
#include <boost/preprocessor/arithmetic/sub.hpp>
#include <boost/preprocessor/array.hpp>
#include <boost/preprocessor/array/data.hpp>
#include <boost/preprocessor/array/detail/get_data.hpp>
#include <boost/preprocessor/array/elem.hpp>
#include <boost/preprocessor/array/enum.hpp>
#include <boost/preprocessor/array/insert.hpp>
#include <boost/preprocessor/array/pop_back.hpp>
#include <boost/preprocessor/array/pop_front.hpp>
#include <boost/preprocessor/array/push_back.hpp>
#include <boost/preprocessor/array/push_front.hpp>
#include <boost/preprocessor/array/remove.hpp>
#include <boost/preprocessor/array/replace.hpp>
#include <boost/preprocessor/array/reverse.hpp>
#include <boost/preprocessor/array/size.hpp>
#include <boost/preprocessor/array/to_list.hpp>
#include <boost/preprocessor/array/to_seq.hpp>
#include <boost/preprocessor/array/to_tuple.hpp>
#include <boost/preprocessor/assert_msg.hpp>
#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/comma.hpp>
#include <boost/preprocessor/comma_if.hpp>
#include <boost/preprocessor/comparison.hpp>
#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/comparison/greater.hpp>
#include <boost/preprocessor/comparison/greater_equal.hpp>
#include <boost/preprocessor/comparison/less.hpp>
#include <boost/preprocessor/comparison/less_equal.hpp>
#include <boost/preprocessor/comparison/limits/not_equal_1024.hpp>
#include <boost/preprocessor/comparison/limits/not_equal_256.hpp>
#include <boost/preprocessor/comparison/limits/not_equal_512.hpp>
#include <boost/preprocessor/comparison/not_equal.hpp>
#include <boost/preprocessor/config/config.hpp>
#include <boost/preprocessor/config/limits.hpp>
#include <boost/preprocessor/control.hpp>
#include <boost/preprocessor/control/deduce_d.hpp>
#include <boost/preprocessor/control/detail/dmc/while.hpp>
#include <boost/preprocessor/control/detail/edg/limits/while_1024.hpp>
#include <boost/preprocessor/control/detail/edg/limits/while_256.hpp>
#include <boost/preprocessor/control/detail/edg/limits/while_512.hpp>
#include <boost/preprocessor/control/detail/edg/while.hpp>
#include <boost/preprocessor/control/detail/limits/while_1024.hpp>
#include <boost/preprocessor/control/detail/limits/while_256.hpp>
#include <boost/preprocessor/control/detail/limits/while_512.hpp>
#include <boost/preprocessor/control/detail/msvc/while.hpp>
#include <boost/preprocessor/control/detail/while.hpp>
#include <boost/preprocessor/control/expr_if.hpp>
#include <boost/preprocessor/control/expr_iif.hpp>
#include <boost/preprocessor/control/if.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/control/limits/while_1024.hpp>
#include <boost/preprocessor/control/limits/while_256.hpp>
#include <boost/preprocessor/control/limits/while_512.hpp>
#include <boost/preprocessor/control/while.hpp>
#include <boost/preprocessor/debug.hpp>
#include <boost/preprocessor/debug/assert.hpp>
#include <boost/preprocessor/debug/error.hpp>
#include <boost/preprocessor/debug/line.hpp>
#include <boost/preprocessor/dec.hpp>
#include <boost/preprocessor/detail/auto_rec.hpp>
#include <boost/preprocessor/detail/check.hpp>
#include <boost/preprocessor/detail/dmc/auto_rec.hpp>
#include <boost/preprocessor/detail/is_binary.hpp>
#include <boost/preprocessor/detail/is_nullary.hpp>
#include <boost/preprocessor/detail/is_unary.hpp>
#include <boost/preprocessor/detail/limits/auto_rec_1024.hpp>
#include <boost/preprocessor/detail/limits/auto_rec_256.hpp>
#include <boost/preprocessor/detail/limits/auto_rec_512.hpp>
#include <boost/preprocessor/detail/null.hpp>
#include <boost/preprocessor/detail/split.hpp>
#include <boost/preprocessor/empty.hpp>
#include <boost/preprocessor/enum.hpp>
#include <boost/preprocessor/enum_params.hpp>
#include <boost/preprocessor/enum_params_with_a_default.hpp>
#include <boost/preprocessor/enum_params_with_defaults.hpp>
#include <boost/preprocessor/enum_shifted.hpp>
#include <boost/preprocessor/enum_shifted_params.hpp>
#include <boost/preprocessor/expand.hpp>
#include <boost/preprocessor/expr_if.hpp>
#include <boost/preprocessor/facilities.hpp>
#include <boost/preprocessor/facilities/apply.hpp>
#include <boost/preprocessor/facilities/check_empty.hpp>
#include <boost/preprocessor/facilities/detail/is_empty.hpp>
#include <boost/preprocessor/facilities/empty.hpp>
#include <boost/preprocessor/facilities/expand.hpp>
#include <boost/preprocessor/facilities/identity.hpp>
#include <boost/preprocessor/facilities/intercept.hpp>
#include <boost/preprocessor/facilities/is_1.hpp>
#include <boost/preprocessor/facilities/is_empty.hpp>
#include <boost/preprocessor/facilities/is_empty_or_1.hpp>
#include <boost/preprocessor/facilities/is_empty_variadic.hpp>
#include <boost/preprocessor/facilities/limits/intercept_1024.hpp>
#include <boost/preprocessor/facilities/limits/intercept_256.hpp>
#include <boost/preprocessor/facilities/limits/intercept_512.hpp>
#include <boost/preprocessor/facilities/overload.hpp>
#include <boost/preprocessor/facilities/va_opt.hpp>
#include <boost/preprocessor/for.hpp>
#include <boost/preprocessor/identity.hpp>
#include <boost/preprocessor/if.hpp>
#include <boost/preprocessor/inc.hpp>
#include <boost/preprocessor/iterate.hpp>
#include <boost/preprocessor/iteration.hpp>
#include <boost/preprocessor/iteration/detail/bounds/lower1.hpp>
#include <boost/preprocessor/iteration/detail/bounds/lower2.hpp>
#include <boost/preprocessor/iteration/detail/bounds/lower3.hpp>
#include <boost/preprocessor/iteration/detail/bounds/lower4.hpp>
#include <boost/preprocessor/iteration/detail/bounds/lower5.hpp>
#include <boost/preprocessor/iteration/detail/bounds/upper1.hpp>
#include <boost/preprocessor/iteration/detail/bounds/upper2.hpp>
#include <boost/preprocessor/iteration/detail/bounds/upper3.hpp>
#include <boost/preprocessor/iteration/detail/bounds/upper4.hpp>
#include <boost/preprocessor/iteration/detail/bounds/upper5.hpp>
#include <boost/preprocessor/iteration/detail/finish.hpp>
#include <boost/preprocessor/iteration/detail/iter/forward1.hpp>
#include <boost/preprocessor/iteration/detail/iter/forward2.hpp>
#include <boost/preprocessor/iteration/detail/iter/forward3.hpp>
#include <boost/preprocessor/iteration/detail/iter/forward4.hpp>
#include <boost/preprocessor/iteration/detail/iter/forward5.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward1_1024.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward1_256.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward1_512.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward2_1024.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward2_256.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward2_512.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward3_1024.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward3_256.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward3_512.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward4_1024.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward4_256.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward4_512.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward5_1024.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward5_256.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/forward5_512.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse1_1024.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse1_256.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse1_512.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse2_1024.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse2_256.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse2_512.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse3_1024.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse3_256.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse3_512.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse4_1024.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse4_256.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse4_512.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse5_1024.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse5_256.hpp>
#include <boost/preprocessor/iteration/detail/iter/limits/reverse5_512.hpp>
#include <boost/preprocessor/iteration/detail/iter/reverse1.hpp>
#include <boost/preprocessor/iteration/detail/iter/reverse2.hpp>
#include <boost/preprocessor/iteration/detail/iter/reverse3.hpp>
#include <boost/preprocessor/iteration/detail/iter/reverse4.hpp>
#include <boost/preprocessor/iteration/detail/iter/reverse5.hpp>
#include <boost/preprocessor/iteration/detail/limits/local_1024.hpp>
#include <boost/preprocessor/iteration/detail/limits/local_256.hpp>
#include <boost/preprocessor/iteration/detail/limits/local_512.hpp>
#include <boost/preprocessor/iteration/detail/limits/rlocal_1024.hpp>
#include <boost/preprocessor/iteration/detail/limits/rlocal_256.hpp>
#include <boost/preprocessor/iteration/detail/limits/rlocal_512.hpp>
#include <boost/preprocessor/iteration/detail/local.hpp>
#include <boost/preprocessor/iteration/detail/rlocal.hpp>
#include <boost/preprocessor/iteration/detail/self.hpp>
#include <boost/preprocessor/iteration/detail/start.hpp>
#include <boost/preprocessor/iteration/iterate.hpp>
#include <boost/preprocessor/iteration/local.hpp>
#include <boost/preprocessor/iteration/self.hpp>
#include <boost/preprocessor/library.hpp>
#include <boost/preprocessor/limits.hpp>
#include <boost/preprocessor/list.hpp>
#include <boost/preprocessor/list/adt.hpp>
#include <boost/preprocessor/list/append.hpp>
#include <boost/preprocessor/list/at.hpp>
#include <boost/preprocessor/list/cat.hpp>
#include <boost/preprocessor/list/detail/dmc/fold_left.hpp>
#include <boost/preprocessor/list/detail/edg/fold_left.hpp>
#include <boost/preprocessor/list/detail/edg/fold_right.hpp>
#include <boost/preprocessor/list/detail/edg/limits/fold_left_1024.hpp>
#include <boost/preprocessor/list/detail/edg/limits/fold_left_256.hpp>
#include <boost/preprocessor/list/detail/edg/limits/fold_left_512.hpp>
#include <boost/preprocessor/list/detail/edg/limits/fold_right_1024.hpp>
#include <boost/preprocessor/list/detail/edg/limits/fold_right_256.hpp>
#include <boost/preprocessor/list/detail/edg/limits/fold_right_512.hpp>
#include <boost/preprocessor/list/detail/fold_left.hpp>
#include <boost/preprocessor/list/detail/fold_right.hpp>
#include <boost/preprocessor/list/detail/limits/fold_left_1024.hpp>
#include <boost/preprocessor/list/detail/limits/fold_left_256.hpp>
#include <boost/preprocessor/list/detail/limits/fold_left_512.hpp>
#include <boost/preprocessor/list/detail/limits/fold_right_1024.hpp>
#include <boost/preprocessor/list/detail/limits/fold_right_256.hpp>
#include <boost/preprocessor/list/detail/limits/fold_right_512.hpp>
#include <boost/preprocessor/list/enum.hpp>
#include <boost/preprocessor/list/filter.hpp>
#include <boost/preprocessor/list/first_n.hpp>
#include <boost/preprocessor/list/fold_left.hpp>
#include <boost/preprocessor/list/fold_right.hpp>
#include <boost/preprocessor/list/for_each.hpp>
#include <boost/preprocessor/list/for_each_i.hpp>
#include <boost/preprocessor/list/for_each_product.hpp>
#include <boost/preprocessor/list/limits/fold_left_1024.hpp>
#include <boost/preprocessor/list/limits/fold_left_256.hpp>
#include <boost/preprocessor/list/limits/fold_left_512.hpp>
#include <boost/preprocessor/list/rest_n.hpp>
#include <boost/preprocessor/list/reverse.hpp>
#include <boost/preprocessor/list/size.hpp>
#include <boost/preprocessor/list/to_array.hpp>
#include <boost/preprocessor/list/to_seq.hpp>
#include <boost/preprocessor/list/to_tuple.hpp>
#include <boost/preprocessor/list/transform.hpp>
#include <boost/preprocessor/logical.hpp>
#include <boost/preprocessor/logical/and.hpp>
#include <boost/preprocessor/logical/bitand.hpp>
#include <boost/preprocessor/logical/bitnor.hpp>
#include <boost/preprocessor/logical/bitor.hpp>
#include <boost/preprocessor/logical/bitxor.hpp>
#include <boost/preprocessor/logical/bool.hpp>
#include <boost/preprocessor/logical/compl.hpp>
#include <boost/preprocessor/logical/limits/bool_1024.hpp>
#include <boost/preprocessor/logical/limits/bool_256.hpp>
#include <boost/preprocessor/logical/limits/bool_512.hpp>
#include <boost/preprocessor/logical/nor.hpp>
#include <boost/preprocessor/logical/not.hpp>
#include <boost/preprocessor/logical/or.hpp>
#include <boost/preprocessor/logical/xor.hpp>
#include <boost/preprocessor/max.hpp>
#include <boost/preprocessor/min.hpp>
#include <boost/preprocessor/punctuation.hpp>
#include <boost/preprocessor/punctuation/comma.hpp>
#include <boost/preprocessor/punctuation/comma_if.hpp>
#include <boost/preprocessor/punctuation/detail/is_begin_parens.hpp>
#include <boost/preprocessor/punctuation/is_begin_parens.hpp>
#include <boost/preprocessor/punctuation/paren.hpp>
#include <boost/preprocessor/punctuation/paren_if.hpp>
#include <boost/preprocessor/punctuation/remove_parens.hpp>
#include <boost/preprocessor/repeat.hpp>
#include <boost/preprocessor/repeat_2nd.hpp>
#include <boost/preprocessor/repeat_3rd.hpp>
#include <boost/preprocessor/repeat_from_to.hpp>
#include <boost/preprocessor/repeat_from_to_2nd.hpp>
#include <boost/preprocessor/repeat_from_to_3rd.hpp>
#include <boost/preprocessor/repetition.hpp>
#include <boost/preprocessor/repetition/deduce_r.hpp>
#include <boost/preprocessor/repetition/deduce_z.hpp>
#include <boost/preprocessor/repetition/detail/dmc/for.hpp>
#include <boost/preprocessor/repetition/detail/edg/for.hpp>
#include <boost/preprocessor/repetition/detail/edg/limits/for_1024.hpp>
#include <boost/preprocessor/repetition/detail/edg/limits/for_256.hpp>
#include <boost/preprocessor/repetition/detail/edg/limits/for_512.hpp>
#include <boost/preprocessor/repetition/detail/for.hpp>
#include <boost/preprocessor/repetition/detail/limits/for_1024.hpp>
#include <boost/preprocessor/repetition/detail/limits/for_256.hpp>
#include <boost/preprocessor/repetition/detail/limits/for_512.hpp>
#include <boost/preprocessor/repetition/detail/msvc/for.hpp>
#include <boost/preprocessor/repetition/enum.hpp>
#include <boost/preprocessor/repetition/enum_binary_params.hpp>
#include <boost/preprocessor/repetition/enum_params.hpp>
#include <boost/preprocessor/repetition/enum_params_with_a_default.hpp>
#include <boost/preprocessor/repetition/enum_params_with_defaults.hpp>
#include <boost/preprocessor/repetition/enum_shifted.hpp>
#include <boost/preprocessor/repetition/enum_shifted_binary_params.hpp>
#include <boost/preprocessor/repetition/enum_shifted_params.hpp>
#include <boost/preprocessor/repetition/enum_trailing.hpp>
#include <boost/preprocessor/repetition/enum_trailing_binary_params.hpp>
#include <boost/preprocessor/repetition/enum_trailing_params.hpp>
#include <boost/preprocessor/repetition/for.hpp>
#include <boost/preprocessor/repetition/limits/for_1024.hpp>
#include <boost/preprocessor/repetition/limits/for_256.hpp>
#include <boost/preprocessor/repetition/limits/for_512.hpp>
#include <boost/preprocessor/repetition/limits/repeat_1024.hpp>
#include <boost/preprocessor/repetition/limits/repeat_256.hpp>
#include <boost/preprocessor/repetition/limits/repeat_512.hpp>
#include <boost/preprocessor/repetition/repeat.hpp>
#include <boost/preprocessor/repetition/repeat_from_to.hpp>
#include <boost/preprocessor/selection.hpp>
#include <boost/preprocessor/selection/max.hpp>
#include <boost/preprocessor/selection/min.hpp>
#include <boost/preprocessor/seq.hpp>
#include <boost/preprocessor/seq/cat.hpp>
#include <boost/preprocessor/seq/detail/binary_transform.hpp>
#include <boost/preprocessor/seq/detail/is_empty.hpp>
#include <boost/preprocessor/seq/detail/limits/split_1024.hpp>
#include <boost/preprocessor/seq/detail/limits/split_256.hpp>
#include <boost/preprocessor/seq/detail/limits/split_512.hpp>
#include <boost/preprocessor/seq/detail/split.hpp>
#include <boost/preprocessor/seq/detail/to_list_msvc.hpp>
#include <boost/preprocessor/seq/elem.hpp>
#include <boost/preprocessor/seq/enum.hpp>
#include <boost/preprocessor/seq/filter.hpp>
#include <boost/preprocessor/seq/first_n.hpp>
#include <boost/preprocessor/seq/fold_left.hpp>
#include <boost/preprocessor/seq/fold_right.hpp>
#include <boost/preprocessor/seq/for_each.hpp>
#include <boost/preprocessor/seq/for_each_i.hpp>
#include <boost/preprocessor/seq/for_each_product.hpp>
#include <boost/preprocessor/seq/insert.hpp>
#include <boost/preprocessor/seq/limits/elem_1024.hpp>
#include <boost/preprocessor/seq/limits/elem_256.hpp>
#include <boost/preprocessor/seq/limits/elem_512.hpp>
#include <boost/preprocessor/seq/limits/enum_1024.hpp>
#include <boost/preprocessor/seq/limits/enum_256.hpp>
#include <boost/preprocessor/seq/limits/enum_512.hpp>
#include <boost/preprocessor/seq/limits/fold_left_1024.hpp>
#include <boost/preprocessor/seq/limits/fold_left_256.hpp>
#include <boost/preprocessor/seq/limits/fold_left_512.hpp>
#include <boost/preprocessor/seq/limits/fold_right_1024.hpp>
#include <boost/preprocessor/seq/limits/fold_right_256.hpp>
#include <boost/preprocessor/seq/limits/fold_right_512.hpp>
#include <boost/preprocessor/seq/limits/size_1024.hpp>
#include <boost/preprocessor/seq/limits/size_256.hpp>
#include <boost/preprocessor/seq/limits/size_512.hpp>
#include <boost/preprocessor/seq/pop_back.hpp>
#include <boost/preprocessor/seq/pop_front.hpp>
#include <boost/preprocessor/seq/push_back.hpp>
#include <boost/preprocessor/seq/push_front.hpp>
#include <boost/preprocessor/seq/remove.hpp>
#include <boost/preprocessor/seq/replace.hpp>
#include <boost/preprocessor/seq/rest_n.hpp>
#include <boost/preprocessor/seq/reverse.hpp>
#include <boost/preprocessor/seq/seq.hpp>
#include <boost/preprocessor/seq/size.hpp>
#include <boost/preprocessor/seq/subseq.hpp>
#include <boost/preprocessor/seq/to_array.hpp>
#include <boost/preprocessor/seq/to_list.hpp>
#include <boost/preprocessor/seq/to_tuple.hpp>
#include <boost/preprocessor/seq/transform.hpp>
#include <boost/preprocessor/seq/variadic_seq_to_seq.hpp>
#include <boost/preprocessor/slot.hpp>
#include <boost/preprocessor/slot/counter.hpp>
#include <boost/preprocessor/slot/detail/counter.hpp>
#include <boost/preprocessor/slot/detail/def.hpp>
#include <boost/preprocessor/slot/detail/shared.hpp>
#include <boost/preprocessor/slot/detail/slot1.hpp>
#include <boost/preprocessor/slot/detail/slot2.hpp>
#include <boost/preprocessor/slot/detail/slot3.hpp>
#include <boost/preprocessor/slot/detail/slot4.hpp>
#include <boost/preprocessor/slot/detail/slot5.hpp>
#include <boost/preprocessor/slot/slot.hpp>
#include <boost/preprocessor/stringize.hpp>
#include <boost/preprocessor/tuple.hpp>
#include <boost/preprocessor/tuple/detail/is_single_return.hpp>
#include <boost/preprocessor/tuple/eat.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/tuple/enum.hpp>
#include <boost/preprocessor/tuple/insert.hpp>
#include <boost/preprocessor/tuple/limits/reverse_128.hpp>
#include <boost/preprocessor/tuple/limits/reverse_256.hpp>
#include <boost/preprocessor/tuple/limits/reverse_64.hpp>
#include <boost/preprocessor/tuple/limits/to_list_128.hpp>
#include <boost/preprocessor/tuple/limits/to_list_256.hpp>
#include <boost/preprocessor/tuple/limits/to_list_64.hpp>
#include <boost/preprocessor/tuple/limits/to_seq_128.hpp>
#include <boost/preprocessor/tuple/limits/to_seq_256.hpp>
#include <boost/preprocessor/tuple/limits/to_seq_64.hpp>
#include <boost/preprocessor/tuple/pop_back.hpp>
#include <boost/preprocessor/tuple/pop_front.hpp>
#include <boost/preprocessor/tuple/push_back.hpp>
#include <boost/preprocessor/tuple/push_front.hpp>
#include <boost/preprocessor/tuple/rem.hpp>
#include <boost/preprocessor/tuple/remove.hpp>
#include <boost/preprocessor/tuple/replace.hpp>
#include <boost/preprocessor/tuple/reverse.hpp>
#include <boost/preprocessor/tuple/size.hpp>
#include <boost/preprocessor/tuple/to_array.hpp>
#include <boost/preprocessor/tuple/to_list.hpp>
#include <boost/preprocessor/tuple/to_seq.hpp>
#include <boost/preprocessor/variadic.hpp>
#include <boost/preprocessor/variadic/detail/has_opt.hpp>
#include <boost/preprocessor/variadic/detail/is_single_return.hpp>
#include <boost/preprocessor/variadic/elem.hpp>
#include <boost/preprocessor/variadic/has_opt.hpp>
#include <boost/preprocessor/variadic/limits/elem_128.hpp>
#include <boost/preprocessor/variadic/limits/elem_256.hpp>
#include <boost/preprocessor/variadic/limits/elem_64.hpp>
#include <boost/preprocessor/variadic/limits/size_128.hpp>
#include <boost/preprocessor/variadic/limits/size_256.hpp>
#include <boost/preprocessor/variadic/limits/size_64.hpp>
#include <boost/preprocessor/variadic/size.hpp>
#include <boost/preprocessor/variadic/to_array.hpp>
#include <boost/preprocessor/variadic/to_list.hpp>
#include <boost/preprocessor/variadic/to_seq.hpp>
#include <boost/preprocessor/variadic/to_tuple.hpp>
#include <boost/preprocessor/while.hpp>
#include <boost/preprocessor/wstringize.hpp>

