
// fix ubiquitous warning C5204: 'boost::blah::blah<Blah>': class has virtual functions, but its trivial destructor is not virtual; instances of objects derived from this class may not be destructed correctly
//
// while this generally CAN/MAY be an issue, we brutally assume that the Boost Boys know their shit and NEVER make this mistake, i.e. the classes/structs in question are *implicitly `final`*!
// To play it kinda safe, we apply this 'please shut up' fix to this dummy=see-if-we-can-compile-Ev'ryTing source file only:

#if defined(_MSC_VER)
#pragma warning(disable: 5204)

// fix/shut up warning C4266: 'void boost::blah::blah::blah(...)': no override available for virtual member function from base 'boost::blah::blah'; function is hidden
#pragma warning(disable: 4266)
#endif

#include <boost/spirit/include/classic.hpp>
#include <boost/spirit/include/classic_actions.hpp>
#include <boost/spirit/include/classic_actor.hpp>
#include <boost/spirit/include/classic_alternative.hpp>
#include <boost/spirit/include/classic_as_parser.hpp>
#include <boost/spirit/include/classic_assert.hpp>
#include <boost/spirit/include/classic_assign_actor.hpp>
#include <boost/spirit/include/classic_assign_key_actor.hpp>
#include <boost/spirit/include/classic_ast.hpp>
#include <boost/spirit/include/classic_ast_fwd.hpp>
#include <boost/spirit/include/classic_attribute.hpp>
#include <boost/spirit/include/classic_basic_chset.hpp>
#include <boost/spirit/include/classic_chset.hpp>
#include <boost/spirit/include/classic_chset_operators.hpp>
#include <boost/spirit/include/classic_clear_actor.hpp>
#include <boost/spirit/include/classic_closure.hpp>
#include <boost/spirit/include/classic_closure_context.hpp>
#include <boost/spirit/include/classic_closure_fwd.hpp>
#include <boost/spirit/include/classic_common.hpp>
#include <boost/spirit/include/classic_common_fwd.hpp>
#include <boost/spirit/include/classic_composite.hpp>
#include <boost/spirit/include/classic_config.hpp>
#include <boost/spirit/include/classic_confix.hpp>
#include <boost/spirit/include/classic_confix_fwd.hpp>
#include <boost/spirit/include/classic_core.hpp>
#include <boost/spirit/include/classic_debug.hpp>
#include <boost/spirit/include/classic_debug_node.hpp>
#include <boost/spirit/include/classic_decrement_actor.hpp>
#include <boost/spirit/include/classic_difference.hpp>
#include <boost/spirit/include/classic_directives.hpp>
#include <boost/spirit/include/classic_distinct.hpp>
#include <boost/spirit/include/classic_distinct_fwd.hpp>
#include <boost/spirit/include/classic_dynamic.hpp>
#include <boost/spirit/include/classic_epsilon.hpp>
#include <boost/spirit/include/classic_erase_actor.hpp>
#include <boost/spirit/include/classic_error_handling.hpp>
#include <boost/spirit/include/classic_escape_char.hpp>
#include <boost/spirit/include/classic_escape_char_fwd.hpp>
#include <boost/spirit/include/classic_exceptions.hpp>
#include <boost/spirit/include/classic_exceptions_fwd.hpp>
#include <boost/spirit/include/classic_exclusive_or.hpp>
#include <boost/spirit/include/classic_file_iterator.hpp>
#include <boost/spirit/include/classic_file_iterator_fwd.hpp>
#include <boost/spirit/include/classic_fixed_size_queue.hpp>
#include <boost/spirit/include/classic_flush_multi_pass.hpp>
#include <boost/spirit/include/classic_for.hpp>
#include <boost/spirit/include/classic_functor_parser.hpp>
#include <boost/spirit/include/classic_fundamental.hpp>
#include <boost/spirit/include/classic_grammar.hpp>
#include <boost/spirit/include/classic_grammar_def.hpp>
#include <boost/spirit/include/classic_grammar_def_fwd.hpp>
#include <boost/spirit/include/classic_if.hpp>
#include <boost/spirit/include/classic_increment_actor.hpp>
#include <boost/spirit/include/classic_insert_at_actor.hpp>
#include <boost/spirit/include/classic_insert_key_actor.hpp>
#include <boost/spirit/include/classic_intersection.hpp>
#include <boost/spirit/include/classic_iterator.hpp>
#include <boost/spirit/include/classic_kleene_star.hpp>
#include <boost/spirit/include/classic_lazy.hpp>
#include <boost/spirit/include/classic_list.hpp>
#include <boost/spirit/include/classic_lists.hpp>
#include <boost/spirit/include/classic_lists_fwd.hpp>
#include <boost/spirit/include/classic_loops.hpp>
#include <boost/spirit/include/classic_match.hpp>
#include <boost/spirit/include/classic_meta.hpp>
#include <boost/spirit/include/classic_minimal.hpp>
#include <boost/spirit/include/classic_multi_pass.hpp>
#include <boost/spirit/include/classic_multi_pass_fwd.hpp>
#include <boost/spirit/include/classic_nil.hpp>
#include <boost/spirit/include/classic_no_actions.hpp>
#include <boost/spirit/include/classic_numerics.hpp>
#include <boost/spirit/include/classic_numerics_fwd.hpp>
#include <boost/spirit/include/classic_operators.hpp>
#include <boost/spirit/include/classic_optional.hpp>
#include <boost/spirit/include/classic_parametric.hpp>
#include <boost/spirit/include/classic_parse_tree.hpp>
#include <boost/spirit/include/classic_parse_tree_fwd.hpp>
#include <boost/spirit/include/classic_parse_tree_utils.hpp>
#include <boost/spirit/include/classic_parser.hpp>
#include <boost/spirit/include/classic_parser_context.hpp>
#include <boost/spirit/include/classic_parser_id.hpp>
#include <boost/spirit/include/classic_parser_names.hpp>
#include <boost/spirit/include/classic_parser_traits.hpp>
#include <boost/spirit/include/classic_position_iterator.hpp>
#include <boost/spirit/include/classic_position_iterator_fwd.hpp>
#include <boost/spirit/include/classic_positive.hpp>
#include <boost/spirit/include/classic_primitives.hpp>
#include <boost/spirit/include/classic_push_back_actor.hpp>
#include <boost/spirit/include/classic_push_front_actor.hpp>
#include <boost/spirit/include/classic_range_run.hpp>
#include <boost/spirit/include/classic_ref_actor.hpp>
#include <boost/spirit/include/classic_ref_const_ref_actor.hpp>
#include <boost/spirit/include/classic_ref_const_ref_const_ref_a.hpp>
#include <boost/spirit/include/classic_ref_const_ref_value_actor.hpp>
#include <boost/spirit/include/classic_ref_value_actor.hpp>
#include <boost/spirit/include/classic_refactoring.hpp>
#include <boost/spirit/include/classic_regex.hpp>
#include <boost/spirit/include/classic_rule.hpp>
#include <boost/spirit/include/classic_rule_alias.hpp>
#include <boost/spirit/include/classic_rule_parser.hpp>
#include <boost/spirit/include/classic_safe_bool.hpp>
#include <boost/spirit/include/classic_scanner.hpp>
#include <boost/spirit/include/classic_scanner_fwd.hpp>
#include <boost/spirit/include/classic_scoped_lock.hpp>
#include <boost/spirit/include/classic_select.hpp>
#include <boost/spirit/include/classic_sequence.hpp>
#include <boost/spirit/include/classic_sequential_and.hpp>
#include <boost/spirit/include/classic_sequential_or.hpp>
#include <boost/spirit/include/classic_skipper.hpp>
#include <boost/spirit/include/classic_skipper_fwd.hpp>
#include <boost/spirit/include/classic_spirit.hpp>
#include <boost/spirit/include/classic_static.hpp>
#include <boost/spirit/include/classic_stored_rule.hpp>
#include <boost/spirit/include/classic_stored_rule_fwd.hpp>
#include <boost/spirit/include/classic_subrule.hpp>
#include <boost/spirit/include/classic_subrule_fwd.hpp>
#include <boost/spirit/include/classic_swap_actor.hpp>
#include <boost/spirit/include/classic_switch.hpp>
#include <boost/spirit/include/classic_symbols.hpp>
#include <boost/spirit/include/classic_symbols_fwd.hpp>
#include <boost/spirit/include/classic_traverse.hpp>
#include <boost/spirit/include/classic_tree_to_xml.hpp>
#include <boost/spirit/include/classic_typeof.hpp>
#include <boost/spirit/include/classic_utility.hpp>
#include <boost/spirit/include/classic_while.hpp>
#include <boost/spirit/include/karma.hpp>
#include <boost/spirit/include/karma_action.hpp>
#include <boost/spirit/include/karma_alternative.hpp>
#include <boost/spirit/include/karma_and_predicate.hpp>
#include <boost/spirit/include/karma_as.hpp>
#include <boost/spirit/include/karma_attr_cast.hpp>
#include <boost/spirit/include/karma_auto.hpp>
#include <boost/spirit/include/karma_auxiliary.hpp>
#include <boost/spirit/include/karma_binary.hpp>
#include <boost/spirit/include/karma_bool.hpp>
#include <boost/spirit/include/karma_buffer.hpp>
#include <boost/spirit/include/karma_center_alignment.hpp>
#include <boost/spirit/include/karma_char.hpp>
#include <boost/spirit/include/karma_char_.hpp>
#include <boost/spirit/include/karma_char_class.hpp>
#include <boost/spirit/include/karma_columns.hpp>
#include <boost/spirit/include/karma_delimit.hpp>
#include <boost/spirit/include/karma_directive.hpp>
#include <boost/spirit/include/karma_domain.hpp>
#include <boost/spirit/include/karma_duplicate.hpp>
#include <boost/spirit/include/karma_eol.hpp>
#include <boost/spirit/include/karma_eps.hpp>
#include <boost/spirit/include/karma_format.hpp>
#include <boost/spirit/include/karma_format_attr.hpp>
#include <boost/spirit/include/karma_format_auto.hpp>
#include <boost/spirit/include/karma_generate.hpp>
#include <boost/spirit/include/karma_generate_attr.hpp>
#include <boost/spirit/include/karma_generate_auto.hpp>
#include <boost/spirit/include/karma_grammar.hpp>
#include <boost/spirit/include/karma_int.hpp>
#include <boost/spirit/include/karma_kleene.hpp>
#include <boost/spirit/include/karma_lazy.hpp>
#include <boost/spirit/include/karma_left_alignment.hpp>
#include <boost/spirit/include/karma_list.hpp>
#include <boost/spirit/include/karma_maxwidth.hpp>
#include <boost/spirit/include/karma_no_delimit.hpp>
#include <boost/spirit/include/karma_nonterminal.hpp>
#include <boost/spirit/include/karma_not_predicate.hpp>
#include <boost/spirit/include/karma_numeric.hpp>
#include <boost/spirit/include/karma_omit.hpp>
#include <boost/spirit/include/karma_operator.hpp>
#include <boost/spirit/include/karma_optional.hpp>
#include <boost/spirit/include/karma_phoenix_attributes.hpp>
#include <boost/spirit/include/karma_plus.hpp>
#include <boost/spirit/include/karma_real.hpp>
#include <boost/spirit/include/karma_repeat.hpp>
#include <boost/spirit/include/karma_right_alignment.hpp>
#include <boost/spirit/include/karma_rule.hpp>
#include <boost/spirit/include/karma_sequence.hpp>
#include <boost/spirit/include/karma_stream.hpp>
#include <boost/spirit/include/karma_strict_relaxed.hpp>
#include <boost/spirit/include/karma_string.hpp>
#include <boost/spirit/include/karma_symbols.hpp>
#include <boost/spirit/include/karma_uint.hpp>
#include <boost/spirit/include/karma_upper_lower_case.hpp>
#include <boost/spirit/include/karma_verbatim.hpp>
#include <boost/spirit/include/karma_what.hpp>
#include <boost/spirit/include/lex.hpp>
#include <boost/spirit/include/lex_char_token_def.hpp>
#include <boost/spirit/include/lex_domain.hpp>
#include <boost/spirit/include/lex_generate_static_lexertl.hpp>
#include <boost/spirit/include/lex_lexer.hpp>
#include <boost/spirit/include/lex_lexertl.hpp>
#include <boost/spirit/include/lex_lexertl_position_token.hpp>
#include <boost/spirit/include/lex_lexertl_token.hpp>
#include <boost/spirit/include/lex_plain_token.hpp>
#include <boost/spirit/include/lex_primitives.hpp>
#include <boost/spirit/include/lex_static_lexertl.hpp>
#include <boost/spirit/include/lex_tokenize_and_parse.hpp>
#include <boost/spirit/include/lex_tokenize_and_parse_attr.hpp>
#include <boost/spirit/include/qi.hpp>
#include <boost/spirit/include/qi_action.hpp>
#include <boost/spirit/include/qi_alternative.hpp>
#include <boost/spirit/include/qi_and_predicate.hpp>
#include <boost/spirit/include/qi_as.hpp>
#include <boost/spirit/include/qi_as_string.hpp>
#include <boost/spirit/include/qi_attr.hpp>
#include <boost/spirit/include/qi_attr_cast.hpp>
#include <boost/spirit/include/qi_auto.hpp>
#include <boost/spirit/include/qi_auxiliary.hpp>
#include <boost/spirit/include/qi_binary.hpp>
#include <boost/spirit/include/qi_bool.hpp>
#include <boost/spirit/include/qi_char.hpp>
#include <boost/spirit/include/qi_char_.hpp>
#include <boost/spirit/include/qi_char_class.hpp>
#include <boost/spirit/include/qi_copy.hpp>
#include <boost/spirit/include/qi_core.hpp>
#include <boost/spirit/include/qi_difference.hpp>
#include <boost/spirit/include/qi_directive.hpp>
#include <boost/spirit/include/qi_domain.hpp>
#include <boost/spirit/include/qi_eoi.hpp>
#include <boost/spirit/include/qi_eol.hpp>
#include <boost/spirit/include/qi_eps.hpp>
#include <boost/spirit/include/qi_expect.hpp>
#include <boost/spirit/include/qi_grammar.hpp>
#include <boost/spirit/include/qi_hold.hpp>
#include <boost/spirit/include/qi_int.hpp>
#include <boost/spirit/include/qi_kleene.hpp>
#include <boost/spirit/include/qi_lazy.hpp>
#include <boost/spirit/include/qi_lexeme.hpp>
#include <boost/spirit/include/qi_list.hpp>
#include <boost/spirit/include/qi_lit.hpp>
#include <boost/spirit/include/qi_match.hpp>
#include <boost/spirit/include/qi_match_attr.hpp>
#include <boost/spirit/include/qi_match_auto.hpp>
#include <boost/spirit/include/qi_matches.hpp>
#include <boost/spirit/include/qi_no_case.hpp>
#include <boost/spirit/include/qi_no_skip.hpp>
#include <boost/spirit/include/qi_nonterminal.hpp>
#include <boost/spirit/include/qi_not_predicate.hpp>
#include <boost/spirit/include/qi_numeric.hpp>
#include <boost/spirit/include/qi_omit.hpp>
#include <boost/spirit/include/qi_operator.hpp>
#include <boost/spirit/include/qi_optional.hpp>
#include <boost/spirit/include/qi_parse.hpp>
#include <boost/spirit/include/qi_parse_attr.hpp>
#include <boost/spirit/include/qi_parse_auto.hpp>
#include <boost/spirit/include/qi_permutation.hpp>
#include <boost/spirit/include/qi_plus.hpp>
#include <boost/spirit/include/qi_raw.hpp>
#include <boost/spirit/include/qi_real.hpp>
#include <boost/spirit/include/qi_repeat.hpp>
#include <boost/spirit/include/qi_rule.hpp>
#include <boost/spirit/include/qi_sequence.hpp>
#include <boost/spirit/include/qi_sequential_or.hpp>
#include <boost/spirit/include/qi_skip.hpp>
#include <boost/spirit/include/qi_stream.hpp>
#include <boost/spirit/include/qi_string.hpp>
#include <boost/spirit/include/qi_symbols.hpp>
#include <boost/spirit/include/qi_uint.hpp>
#include <boost/spirit/include/qi_what.hpp>
#include <boost/spirit/include/support.hpp>
#include <boost/spirit/include/support_adapt_adt_attributes.hpp>
#include <boost/spirit/include/support_any.hpp>
#include <boost/spirit/include/support_any_if.hpp>
#include <boost/spirit/include/support_any_if_ns.hpp>
#include <boost/spirit/include/support_any_if_ns_so.hpp>
#include <boost/spirit/include/support_any_ns.hpp>
#include <boost/spirit/include/support_any_ns_so.hpp>
#include <boost/spirit/include/support_argument.hpp>
#include <boost/spirit/include/support_ascii.hpp>
#include <boost/spirit/include/support_attributes.hpp>
#include <boost/spirit/include/support_attributes_fwd.hpp>
#include <boost/spirit/include/support_auto.hpp>
#include <boost/spirit/include/support_char_class.hpp>
#include <boost/spirit/include/support_container.hpp>
#include <boost/spirit/include/support_extended_variant.hpp>
#include <boost/spirit/include/support_info.hpp>
#include <boost/spirit/include/support_iso8859_1.hpp>
#include <boost/spirit/include/support_istream_iterator.hpp>
#include <boost/spirit/include/support_line_pos_iterator.hpp>
#include <boost/spirit/include/support_locals.hpp>
#include <boost/spirit/include/support_look_ahead.hpp>
#include <boost/spirit/include/support_modify.hpp>
#include <boost/spirit/include/support_multi_pass.hpp>
#include <boost/spirit/include/support_multi_pass_fwd.hpp>
#include <boost/spirit/include/support_ostream_iterator.hpp>
#include <boost/spirit/include/support_standard.hpp>
#include <boost/spirit/include/support_standard_wide.hpp>
#include <boost/spirit/include/support_string_traits.hpp>
#include <boost/spirit/include/support_unused.hpp>
#include <boost/spirit/include/support_utree.hpp>

