
// fix ubiquitous warning C5204: 'boost::blah::blah<Blah>': class has virtual functions, but its trivial destructor is not virtual; instances of objects derived from this class may not be destructed correctly
//
// while this generally CAN/MAY be an issue, we brutally assume that the Boost Boys know their shit and NEVER make this mistake, i.e. the classes/structs in question are *implicitly `final`*!
// To play it kinda safe, we apply this 'please shut up' fix to this dummy=see-if-we-can-compile-Ev'ryTing source file only:

#if defined(_MSC_VER)
#pragma warning(disable: 5204)

// fix/shut up warning C4266: 'void boost::blah::blah::blah(...)': no override available for virtual member function from base 'boost::blah::blah'; function is hidden
#pragma warning(disable: 4266)
#endif

#include <boost/metaparse.hpp>
#include <boost/metaparse/accept.hpp>
#include <boost/metaparse/accept_tag.hpp>
#include <boost/metaparse/accept_when.hpp>
#include <boost/metaparse/alphanum.hpp>
#include <boost/metaparse/always.hpp>
#include <boost/metaparse/always_c.hpp>
#include <boost/metaparse/build_parser.hpp>
#include <boost/metaparse/change_error_message.hpp>
#include <boost/metaparse/config.hpp>
#include <boost/metaparse/debug_parsing_error.hpp>
#include <boost/metaparse/define_error.hpp>
#include <boost/metaparse/digit.hpp>
#include <boost/metaparse/digit_val.hpp>
#include <boost/metaparse/empty.hpp>
#include <boost/metaparse/entire_input.hpp>
#include <boost/metaparse/error/digit_expected.hpp>
#include <boost/metaparse/error/end_of_input_expected.hpp>
#include <boost/metaparse/error/index_out_of_range.hpp>
#include <boost/metaparse/error/letter_expected.hpp>
#include <boost/metaparse/error/literal_expected.hpp>
#include <boost/metaparse/error/none_of_the_expected_cases_found.hpp>
#include <boost/metaparse/error/unexpected_character.hpp>
#include <boost/metaparse/error/unexpected_end_of_input.hpp>
#include <boost/metaparse/error/unpaired.hpp>
#include <boost/metaparse/error/whitespace_expected.hpp>
#include <boost/metaparse/except.hpp>
#include <boost/metaparse/fail.hpp>
#include <boost/metaparse/fail_at_first_char_expected.hpp>
#include <boost/metaparse/fail_tag.hpp>
#include <boost/metaparse/first_of.hpp>
#include <boost/metaparse/foldl.hpp>
#include <boost/metaparse/foldl1.hpp>
#include <boost/metaparse/foldl_reject_incomplete.hpp>
#include <boost/metaparse/foldl_reject_incomplete1.hpp>
#include <boost/metaparse/foldl_reject_incomplete_start_with_parser.hpp>
#include <boost/metaparse/foldl_start_with_parser.hpp>
#include <boost/metaparse/foldr.hpp>
#include <boost/metaparse/foldr1.hpp>
#include <boost/metaparse/foldr_reject_incomplete.hpp>
#include <boost/metaparse/foldr_reject_incomplete1.hpp>
#include <boost/metaparse/foldr_start_with_parser.hpp>
#include <boost/metaparse/get_col.hpp>
#include <boost/metaparse/get_line.hpp>
#include <boost/metaparse/get_message.hpp>
#include <boost/metaparse/get_position.hpp>
#include <boost/metaparse/get_prev_char.hpp>
#include <boost/metaparse/get_remaining.hpp>
#include <boost/metaparse/get_result.hpp>
#include <boost/metaparse/grammar.hpp>
#include <boost/metaparse/if_.hpp>
#include <boost/metaparse/int_.hpp>
#include <boost/metaparse/is_error.hpp>
#include <boost/metaparse/iterate.hpp>
#include <boost/metaparse/iterate_c.hpp>
#include <boost/metaparse/keyword.hpp>
#include <boost/metaparse/last_of.hpp>
#include <boost/metaparse/letter.hpp>
#include <boost/metaparse/limit_one_char_except_size.hpp>
#include <boost/metaparse/limit_one_of_size.hpp>
#include <boost/metaparse/limit_sequence_size.hpp>
#include <boost/metaparse/limit_string_size.hpp>
#include <boost/metaparse/lit.hpp>
#include <boost/metaparse/lit_c.hpp>
#include <boost/metaparse/look_ahead.hpp>
#include <boost/metaparse/middle_of.hpp>
#include <boost/metaparse/next_char.hpp>
#include <boost/metaparse/next_line.hpp>
#include <boost/metaparse/nth_of.hpp>
#include <boost/metaparse/nth_of_c.hpp>
#include <boost/metaparse/one_char.hpp>
#include <boost/metaparse/one_char_except.hpp>
#include <boost/metaparse/one_char_except_c.hpp>
#include <boost/metaparse/one_of.hpp>
#include <boost/metaparse/one_of_c.hpp>
#include <boost/metaparse/optional.hpp>
#include <boost/metaparse/range.hpp>
#include <boost/metaparse/range_c.hpp>
#include <boost/metaparse/reject.hpp>
#include <boost/metaparse/repeated.hpp>
#include <boost/metaparse/repeated1.hpp>
#include <boost/metaparse/repeated_one_of.hpp>
#include <boost/metaparse/repeated_one_of1.hpp>
#include <boost/metaparse/repeated_reject_incomplete.hpp>
#include <boost/metaparse/repeated_reject_incomplete1.hpp>
#include <boost/metaparse/return_.hpp>
#include <boost/metaparse/sequence.hpp>
#include <boost/metaparse/sequence_apply.hpp>
#include <boost/metaparse/source_position.hpp>
#include <boost/metaparse/source_position_tag.hpp>
#include <boost/metaparse/space.hpp>
#include <boost/metaparse/spaces.hpp>
#include <boost/metaparse/start.hpp>
#include <boost/metaparse/string.hpp>
#include <boost/metaparse/string_tag.hpp>
#include <boost/metaparse/string_value.hpp>
#include <boost/metaparse/token.hpp>
#include <boost/metaparse/transform.hpp>
#include <boost/metaparse/transform_error.hpp>
#include <boost/metaparse/transform_error_message.hpp>
#include <boost/metaparse/unless_error.hpp>
#include <boost/metaparse/util/digit_to_int.hpp>
#include <boost/metaparse/util/digit_to_int_c.hpp>
#include <boost/metaparse/util/in_range.hpp>
#include <boost/metaparse/util/in_range_c.hpp>
#include <boost/metaparse/util/int_to_digit.hpp>
#include <boost/metaparse/util/int_to_digit_c.hpp>
#include <boost/metaparse/util/is_digit.hpp>
#include <boost/metaparse/util/is_lcase_letter.hpp>
#include <boost/metaparse/util/is_letter.hpp>
#include <boost/metaparse/util/is_ucase_letter.hpp>
#include <boost/metaparse/util/is_whitespace.hpp>
#include <boost/metaparse/util/is_whitespace_c.hpp>
#include <boost/metaparse/v1/accept.hpp>
#include <boost/metaparse/v1/accept_tag.hpp>
#include <boost/metaparse/v1/accept_when.hpp>
#include <boost/metaparse/v1/alphanum.hpp>
#include <boost/metaparse/v1/always.hpp>
#include <boost/metaparse/v1/always_c.hpp>
#include <boost/metaparse/v1/build_parser.hpp>
#include <boost/metaparse/v1/change_error_message.hpp>
#include <boost/metaparse/v1/cpp11/first_of.hpp>
#include <boost/metaparse/v1/cpp11/fwd/string.hpp>
#include <boost/metaparse/v1/cpp11/last_of.hpp>
#include <boost/metaparse/v1/cpp11/nth_of.hpp>
#include <boost/metaparse/v1/cpp11/nth_of_c.hpp>
#include <boost/metaparse/v1/cpp11/one_char_except.hpp>
#include <boost/metaparse/v1/cpp11/one_char_except_c.hpp>
#include <boost/metaparse/v1/cpp11/one_of.hpp>
#include <boost/metaparse/v1/cpp11/one_of_c.hpp>
#include <boost/metaparse/v1/cpp11/repeated_one_of.hpp>
#include <boost/metaparse/v1/cpp11/repeated_one_of1.hpp>
#include <boost/metaparse/v1/cpp11/sequence.hpp>
#include <boost/metaparse/v1/cpp11/string.hpp>
#include <boost/metaparse/v1/cpp14/one_of_c.hpp>
#include <boost/metaparse/v1/cpp98/first_of.hpp>
#include <boost/metaparse/v1/cpp98/fwd/string.hpp>
#include <boost/metaparse/v1/cpp98/last_of.hpp>
#include <boost/metaparse/v1/cpp98/nth_of.hpp>
#include <boost/metaparse/v1/cpp98/nth_of_c.hpp>
#include <boost/metaparse/v1/cpp98/one_char_except.hpp>
#include <boost/metaparse/v1/cpp98/one_char_except_c.hpp>
#include <boost/metaparse/v1/cpp98/one_of.hpp>
#include <boost/metaparse/v1/cpp98/one_of_c.hpp>
#include <boost/metaparse/v1/cpp98/repeated_one_of.hpp>
#include <boost/metaparse/v1/cpp98/repeated_one_of1.hpp>
#include <boost/metaparse/v1/cpp98/sequence.hpp>
#include <boost/metaparse/v1/cpp98/string.hpp>
#include <boost/metaparse/v1/debug_parsing_error.hpp>
#include <boost/metaparse/v1/define_error.hpp>
#include <boost/metaparse/v1/digit.hpp>
#include <boost/metaparse/v1/digit_val.hpp>
#include <boost/metaparse/v1/empty.hpp>
#include <boost/metaparse/v1/entire_input.hpp>
#include <boost/metaparse/v1/error/digit_expected.hpp>
#include <boost/metaparse/v1/error/end_of_input_expected.hpp>
#include <boost/metaparse/v1/error/expected_to_fail.hpp>
#include <boost/metaparse/v1/error/index_out_of_range.hpp>
#include <boost/metaparse/v1/error/letter_expected.hpp>
#include <boost/metaparse/v1/error/literal_expected.hpp>
#include <boost/metaparse/v1/error/none_of_the_expected_cases_found.hpp>
#include <boost/metaparse/v1/error/unexpected_character.hpp>
#include <boost/metaparse/v1/error/unexpected_end_of_input.hpp>
#include <boost/metaparse/v1/error/unpaired.hpp>
#include <boost/metaparse/v1/error/whitespace_expected.hpp>
#include <boost/metaparse/v1/except.hpp>
#include <boost/metaparse/v1/fail.hpp>
#include <boost/metaparse/v1/fail_at_first_char_expected.hpp>
#include <boost/metaparse/v1/fail_tag.hpp>
#include <boost/metaparse/v1/first_of.hpp>
#include <boost/metaparse/v1/foldl.hpp>
#include <boost/metaparse/v1/foldl1.hpp>
#include <boost/metaparse/v1/foldl_reject_incomplete.hpp>
#include <boost/metaparse/v1/foldl_reject_incomplete1.hpp>
#include <boost/metaparse/v1/foldl_reject_incomplete_start_with_parser.hpp>
#include <boost/metaparse/v1/foldl_start_with_parser.hpp>
#include <boost/metaparse/v1/foldr.hpp>
#include <boost/metaparse/v1/foldr1.hpp>
#include <boost/metaparse/v1/foldr_reject_incomplete.hpp>
#include <boost/metaparse/v1/foldr_reject_incomplete1.hpp>
#include <boost/metaparse/v1/foldr_start_with_parser.hpp>
#include <boost/metaparse/v1/fwd/accept.hpp>
#include <boost/metaparse/v1/fwd/build_parser.hpp>
#include <boost/metaparse/v1/fwd/get_col.hpp>
#include <boost/metaparse/v1/fwd/get_line.hpp>
#include <boost/metaparse/v1/fwd/get_message.hpp>
#include <boost/metaparse/v1/fwd/get_position.hpp>
#include <boost/metaparse/v1/fwd/get_prev_char.hpp>
#include <boost/metaparse/v1/fwd/get_remaining.hpp>
#include <boost/metaparse/v1/fwd/get_result.hpp>
#include <boost/metaparse/v1/fwd/next_char.hpp>
#include <boost/metaparse/v1/fwd/next_line.hpp>
#include <boost/metaparse/v1/fwd/reject.hpp>
#include <boost/metaparse/v1/fwd/source_position.hpp>
#include <boost/metaparse/v1/fwd/string.hpp>
#include <boost/metaparse/v1/get_col.hpp>
#include <boost/metaparse/v1/get_line.hpp>
#include <boost/metaparse/v1/get_message.hpp>
#include <boost/metaparse/v1/get_position.hpp>
#include <boost/metaparse/v1/get_prev_char.hpp>
#include <boost/metaparse/v1/get_remaining.hpp>
#include <boost/metaparse/v1/get_result.hpp>
#include <boost/metaparse/v1/grammar.hpp>
#include <boost/metaparse/v1/if_.hpp>
#include <boost/metaparse/v1/int_.hpp>
#include <boost/metaparse/v1/is_error.hpp>
#include <boost/metaparse/v1/iterate.hpp>
#include <boost/metaparse/v1/iterate_c.hpp>
#include <boost/metaparse/v1/keyword.hpp>
#include <boost/metaparse/v1/last_of.hpp>
#include <boost/metaparse/v1/letter.hpp>
#include <boost/metaparse/v1/lit.hpp>
#include <boost/metaparse/v1/lit_c.hpp>
#include <boost/metaparse/v1/look_ahead.hpp>
#include <boost/metaparse/v1/middle_of.hpp>
#include <boost/metaparse/v1/next_char.hpp>
#include <boost/metaparse/v1/next_line.hpp>
#include <boost/metaparse/v1/nth_of.hpp>
#include <boost/metaparse/v1/nth_of_c.hpp>
#include <boost/metaparse/v1/one_char.hpp>
#include <boost/metaparse/v1/one_char_except.hpp>
#include <boost/metaparse/v1/one_char_except_c.hpp>
#include <boost/metaparse/v1/one_of.hpp>
#include <boost/metaparse/v1/one_of_c.hpp>
#include <boost/metaparse/v1/optional.hpp>
#include <boost/metaparse/v1/range.hpp>
#include <boost/metaparse/v1/range_c.hpp>
#include <boost/metaparse/v1/reject.hpp>
#include <boost/metaparse/v1/repeated.hpp>
#include <boost/metaparse/v1/repeated1.hpp>
#include <boost/metaparse/v1/repeated_one_of.hpp>
#include <boost/metaparse/v1/repeated_one_of1.hpp>
#include <boost/metaparse/v1/repeated_reject_incomplete.hpp>
#include <boost/metaparse/v1/repeated_reject_incomplete1.hpp>
#include <boost/metaparse/v1/return_.hpp>
#include <boost/metaparse/v1/sequence.hpp>
#include <boost/metaparse/v1/sequence_apply.hpp>
#include <boost/metaparse/v1/source_position.hpp>
#include <boost/metaparse/v1/source_position_tag.hpp>
#include <boost/metaparse/v1/space.hpp>
#include <boost/metaparse/v1/spaces.hpp>
#include <boost/metaparse/v1/start.hpp>
#include <boost/metaparse/v1/string.hpp>
#include <boost/metaparse/v1/string_tag.hpp>
#include <boost/metaparse/v1/string_value.hpp>
#include <boost/metaparse/v1/swap.hpp>
#include <boost/metaparse/v1/token.hpp>
#include <boost/metaparse/v1/transform.hpp>
#include <boost/metaparse/v1/transform_error.hpp>
#include <boost/metaparse/v1/transform_error_message.hpp>
#include <boost/metaparse/v1/unless_error.hpp>
#include <boost/metaparse/v1/util/digit_to_int.hpp>
#include <boost/metaparse/v1/util/digit_to_int_c.hpp>
#include <boost/metaparse/v1/util/in_range.hpp>
#include <boost/metaparse/v1/util/in_range_c.hpp>
#include <boost/metaparse/v1/util/int_to_digit.hpp>
#include <boost/metaparse/v1/util/int_to_digit_c.hpp>
#include <boost/metaparse/v1/util/is_digit.hpp>
#include <boost/metaparse/v1/util/is_lcase_letter.hpp>
#include <boost/metaparse/v1/util/is_letter.hpp>
#include <boost/metaparse/v1/util/is_ucase_letter.hpp>
#include <boost/metaparse/v1/util/is_whitespace.hpp>
#include <boost/metaparse/v1/util/is_whitespace_c.hpp>

