
#if __has_include(<pyconfig.h>)

#include <boost/python.hpp>
#include <boost/python/arg_from_python.hpp>
#include <boost/python/args.hpp>
#include <boost/python/args_fwd.hpp>
#include <boost/python/back_reference.hpp>
#include <boost/python/base_type_traits.hpp>
#include <boost/python/bases.hpp>
#include <boost/python/borrowed.hpp>
#include <boost/python/call.hpp>
#include <boost/python/call_method.hpp>
#include <boost/python/cast.hpp>
#include <boost/python/class.hpp>
#include <boost/python/class_fwd.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/copy_non_const_reference.hpp>
#include <boost/python/data_members.hpp>
#include <boost/python/def.hpp>
#include <boost/python/def_visitor.hpp>
#include <boost/python/dict.hpp>
#include <boost/python/docstring_options.hpp>
#include <boost/python/enum.hpp>
#include <boost/python/errors.hpp>
#include <boost/python/exception_translator.hpp>
#include <boost/python/exec.hpp>
#include <boost/python/extract.hpp>
#include <boost/python/handle.hpp>
#include <boost/python/handle_fwd.hpp>
#include <boost/python/has_back_reference.hpp>
#include <boost/python/implicit.hpp>
#include <boost/python/import.hpp>
#include <boost/python/init.hpp>
#include <boost/python/instance_holder.hpp>
#include <boost/python/iterator.hpp>
#include <boost/python/list.hpp>
#include <boost/python/long.hpp>
#include <boost/python/lvalue_from_pytype.hpp>
#include <boost/python/make_constructor.hpp>
#include <boost/python/make_function.hpp>
#include <boost/python/manage_new_object.hpp>
#include <boost/python/module.hpp>
#include <boost/python/module_init.hpp>
#include <boost/python/numpy.hpp>
#include <boost/python/object.hpp>
#include <boost/python/object_attributes.hpp>
#include <boost/python/object_call.hpp>
#include <boost/python/object_core.hpp>
#include <boost/python/object_fwd.hpp>
#include <boost/python/object_items.hpp>
#include <boost/python/object_operators.hpp>
#include <boost/python/object_protocol.hpp>
#include <boost/python/object_protocol_core.hpp>
#include <boost/python/object_slices.hpp>
#include <boost/python/opaque_pointer_converter.hpp>
#include <boost/python/operators.hpp>
#include <boost/python/other.hpp>
#include <boost/python/overloads.hpp>
#include <boost/python/override.hpp>
#include <boost/python/pointee.hpp>
#include <boost/python/proxy.hpp>
#include <boost/python/ptr.hpp>
#include <boost/python/pure_virtual.hpp>
#include <boost/python/raw_function.hpp>
#include <boost/python/refcount.hpp>
#include <boost/python/reference_existing_object.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <boost/python/return_arg.hpp>
#include <boost/python/return_by_value.hpp>
#include <boost/python/return_internal_reference.hpp>
#include <boost/python/return_opaque_pointer.hpp>
#include <boost/python/return_value_policy.hpp>
#include <boost/python/scope.hpp>
#include <boost/python/self.hpp>
#include <boost/python/signature.hpp>
#include <boost/python/slice.hpp>
#include <boost/python/slice_nil.hpp>
#include <boost/python/ssize_t.hpp>
#include <boost/python/stl_iterator.hpp>
#include <boost/python/str.hpp>
#include <boost/python/tag.hpp>
#include <boost/python/to_python_converter.hpp>
#include <boost/python/to_python_indirect.hpp>
#include <boost/python/to_python_value.hpp>
#include <boost/python/tuple.hpp>
#include <boost/python/type_id.hpp>
#include <boost/python/with_custodian_and_ward.hpp>
#include <boost/python/wrapper.hpp>

#endif
