language: C
git:
  depth: 9999999
os:
- linux
compiler:
- clang
matrix:
  include:
  - os: linux
    compiler: gcc
    env: DEPLOY=yes DEPLOY_DEB=yes
  - os: linux
    compiler: gcc
    env: DEPLOY=yes DEPLOY_RPM=yes
  - os: osx
    compiler: clang
    env: DEPLOY=yes
  - os: linux
    compiler: gcc
    env: CROSS=mingw64 DEPLOY=yes
dist: trusty
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
install: |-
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
      sudo apt-get -qy install freeglut3 # Manual installation of the last 2 shouldn't be required, but it is now…
  elif [ "$TRAVIS_OS_NAME" == "osx" ]
  then
    brew update
    brew install sdl2
  fi
script: |-
  if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  ./build.sh || exit 1
  if [ "$DEPLOY_DEB" == "yes" ] || [ "$DEPLOY_RPM" == "yes" ]
  then
    pushd release_build
    make package
    popd
  fi
before_deploy: |-
  if [ "$TRAVIS_OS_NAME" == "osx" ]
  then
    export DEPLOY_FILES=$(ls mupdf-*.dmg)
  elif [ "$CROSS" == "mingw64" ]
  then
    export DEPLOY_FILES=bin/mupdf-gl.exe
  elif [ "$DEPLOY_DEB" == "yes" ]
  then
    export DEPLOY_FILES=$(ls mupdf-*.deb)
  elif [ "$DEPLOY_RPM" == "yes" ]
  then
    export DEPLOY_FILES=$(ls mupdf-*.rpm)
  fi
deploy:
  provider: releases
  api_key:
    secure: L6K
  file: "${DEPLOY_FILES}"
  skip_cleanup: true
  on:
    tags: true
    condition: "$DEPLOY == yes"
    repo: inflex/mupdf
