#! /bin/bash
#
# Generated by the utility: ../../../util/collect_git_checked_out_branch_recusively.sh 
#
# Checkout each git repository to the given branch/commit or list them
#

mode=h;
while getopts ":hlc" opt ; do
  #echo opt+arg = "$opt$OPTARG"
  case "$opt$OPTARG" in
  l )
    mode=h;
    ;;

  c )
    mode=c;
    ;;

  r )
    mode=r;
    ;;

  * )
    cat <<EOH
checkout_to_known_git_branches_recursive.sh options

Options:

-h      : print this help 
-l      : LIST the branch/commit for each git repository (directory) registered in this script.
-c      : CHECKOUT each git repository to the BRANCH registered in this script.
-r      : CHECKOUT/REVERT each git repository to the COMMIT registered in this script.

Note:

Use the '-r' option to set each repository to an exact commit position, which is useful if,
for instance, you wish to reproduce this registered previous software state (which may 
represent a software release) which you wish to analyze/debug.

EOH
    exit 1;
    ;;
  esac
done

if test "$mode" = "h" ; then
  cat <<EOH

Git repository directory                    :: commit hash                         / branch name
--------------------------------------------::--------------------------------------------------
EOH
fi



# args: DIR COMMIT [BRANCH]
git_repo_checkout_branch() {
  if test "$mode" = "c" || test "$mode" = "r" ; then
    if test -d "$1" ; then
      pushd "$1"                                                               2> /dev/null  > /dev/null
      if test "$mode" = "c" ; then
        if test -n "$3" ; then
          # make sure the branch is created locally and is a tracking branch:
          git branch --track "$3" "remotes/origin/$3"                            2> /dev/null  > /dev/null
          git checkout "$3"
        else
          git checkout master
        fi
      else
        git checkout "$2"
      fi
      popd                                                                     2> /dev/null  > /dev/null
    fi
  else
    if test -d "$1" ; then
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
    else
      printf "%-43s :: %s / %s\n" "[DIRECTORY DOES NOT EXIST!] $1" "$2" "$3"
    fi
  fi
}


#
# Make sure we switch to the utility directory as all the relative paths for the repositories
# are based off that path!
#
pushd $(dirname $0)                                                            2> /dev/null  > /dev/null



#
# The registered repositories:
#

git_repo_checkout_branch "../thirdparty/curl" e438f3f36b68eb66cc6f53da779afb06988b1d6d mupdf
git_repo_checkout_branch "../thirdparty/freeglut" ee78761fee8bfe084e65ba6233994756a6d1ac99 master
git_repo_checkout_branch "../thirdparty/freetype" 778dc3d37b518a6ecd5dfaaced46c48b4a8b4414 master
git_repo_checkout_branch "../thirdparty/gumbo-parser" dd001d9eecaa8ab8773d25dea559cfc7dce53e8e 
git_repo_checkout_branch "../thirdparty/harfbuzz" 812c0114f65f0f4b97c45d1ca10986f4d2a24165 mupdf
git_repo_checkout_branch "../thirdparty/jbig2dec" 547f6f7175fcb84cd76141435cb46e59b77d4253 master
git_repo_checkout_branch "../thirdparty/lcms2" 40cf05c1875ba6af3fec2b4ff0353f7a26140ea6 master
git_repo_checkout_branch "../thirdparty/leptonica" f74f7a63d076272f51f90041840794350b6d27b3 master
git_repo_checkout_branch "../thirdparty/libjpeg" 2cb9121a49129a75c86762a50a5ce981cdb33e59 master
git_repo_checkout_branch "../thirdparty/mujs" a6d4858c809d43bb517d572423f06e1a6052b042 mupdf
git_repo_checkout_branch "../thirdparty/openjpeg" af68b4775b4676712b6cd7773711e23733ff2188 bleeding_edge
git_repo_checkout_branch "../thirdparty/tesseract" d33edbc4b19b794a1f979551f89f083d398abe19 master
git_repo_checkout_branch "../thirdparty/zlib" c8d407e68bf40d4322c4fc25850ba9629c7a5761 master

# --- all done ---

popd                                                                           2> /dev/null  > /dev/null

