#! /bin/bash
# generated by collect_git_remote_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"

getopts ":fqh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="f"

  git submodule sync
  git submodule update --init
  git submodule update --init --recursive

  util/git_checkout_submodules_head.sh
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="q"
  ;;

* )
  cat <<EOT
$0 [-f] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. check out the preferred branch for each submodule
           and register all submodule remotes.
-q       : 'quick', i.e. only register all submodule remotes.
submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.

EOT
  exit
  ;;
esac


submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    #echo register_remote [$path] [$name] [$repo] [$argc] [...]

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if test $hit -ne 0 ; then
        if test -d $path && test -s $path/.git ; then
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
                git remote rm $name
            fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}






register_remote .                                                             ArtifexSoftware                          git@github.com:ArtifexSoftware/mupdf.git                                         $# $@
register_remote .                                                             ArtifexSoftware-original                 git@github.com:ArtifexSoftware/mupdf.git                                         $# $@
register_remote .                                                             DaPa                                     git@github.com:DaPa/mupdf.git                                                    $# $@
register_remote .                                                             Dushistov                                git@github.com:Dushistov/mupdf.git                                               $# $@
register_remote .                                                             Ensiss                                   git@github.com:Ensiss/mupdf.git                                                  $# $@
register_remote .                                                             EvoGroupTN                               git@github.com:EvoGroupTN/mupdf.git                                              $# $@
register_remote .                                                             FabriceSalvaire                          git@github.com:FabriceSalvaire/mupdf-v1.3.git                                    $# $@
register_remote .                                                             GerHobbelt                               git@github.com:GerHobbelt/mupdf.git                                              $# $@
register_remote .                                                             MailbirdInc                              git@github.com:MailbirdInc/mupdf.git                                             $# $@
register_remote .                                                             Ordissimo                                git@github.com:Ordissimo/mupdf.git                                               $# $@
register_remote .                                                             RekGRpth                                 git@github.com:RekGRpth/mupdf.git                                                $# $@
register_remote .                                                             alextooter                               git@github.com:alextooter/Cocoa-mupdf.git                                        $# $@
register_remote .                                                             amba                                     git@github.com:amba/mupdf.git                                                    $# $@
register_remote .                                                             arbitrary-dev                            git@github.com:arbitrary-dev/mupdf.git                                           $# $@
register_remote .                                                             artifex-local                            ../../tmp/mupdf/                                                                 $# $@
register_remote .                                                             asine                                    git@github.com:asine/mupdf.git                                                   $# $@
register_remote .                                                             baskerville                              git@github.com:baskerville/mupdf.git                                             $# $@
register_remote .                                                             bloodstalker                             git@github.com:bloodstalker/mupdf.git                                            $# $@
register_remote .                                                             ccxvii                                   git@github.com:ccxvii/mupdf.git                                                  $# $@
register_remote .                                                             cgie                                     git@github.com:cgie/mupdf.git                                                    $# $@
register_remote .                                                             coypoop                                  git@github.com:coypoop/mupdf.git                                                 $# $@
register_remote .                                                             cube-soft                                git@github.com:cube-soft/mupdf.git                                               $# $@
register_remote .                                                             grchen                                   git@github.com:grchen/Cocoa-mupdf.git                                            $# $@
register_remote .                                                             insidenothing                            git@github.com:insidenothing/mupdf.git                                           $# $@
register_remote .                                                             joaomacp                                 git@github.com:joaomacp/mupdf.git                                                $# $@
register_remote .                                                             kartaris                                 git@github.com:kartaris/mupdf.git                                                $# $@
register_remote .                                                             kazuyaujihara                            git@github.com:kazuyaujihara/mupdf.git                                           $# $@
register_remote .                                                             kluete                                   git@github.com:kluete/mupdf.git                                                  $# $@
register_remote .                                                             michaelforney                            git@github.com:michaelforney/mupdf.git                                           $# $@
register_remote .                                                             moronigranja                             git@github.com:moronigranja/mupdf.git                                            $# $@
register_remote .                                                             n1tehawk                                 git@github.com:n1tehawk/mupdf.git                                                $# $@
register_remote .                                                             openrm                                   git@github.com:openrm/mupdf.git                                                  $# $@
register_remote .                                                             pathway27                                git@github.com:pathway27/mupdf.git                                               $# $@
register_remote .                                                             poor-grad-student                        git@github.com:poor-grad-student/mupdf.git                                       $# $@
register_remote .                                                             probonopd                                git@github.com:probonopd/mupdf.git                                               $# $@
register_remote .                                                             quite                                    git@github.com:quite/mupdf.git                                                   $# $@
register_remote .                                                             rakex                                    git@github.com:rakex/mupdf.git                                                   $# $@
register_remote .                                                             rauldoblem                               git@github.com:rauldoblem/MuPdf.Sharp.git                                        $# $@
register_remote .                                                             ruslanfedoseenko                         git@github.com:ruslanfedoseenko/MuPdf.Sharp.git                                  $# $@
register_remote .                                                             sebras                                   git@github.com:sebras/mupdf.git                                                  $# $@
register_remote .                                                             sl424                                    git@github.com:sl424/mupdf.git                                                   $# $@
register_remote .                                                             softkannan                               git@github.com:softkannan/mupdf.git                                              $# $@
register_remote .                                                             uniquehaojie0713                         git@github.com:uniquehaojie0713/mupdf.git                                        $# $@
register_remote .                                                             vinpublic                                git@github.com:vinpublic/mupdf.git                                               $# $@
register_remote .                                                             welat09                                  git@github.com:welat09/mupdf.git                                                 $# $@
register_remote .                                                             wmjordan                                 git@github.com:wmjordan/mupdf.git                                                $# $@
register_remote .                                                             wmjordan-MuPDFSharp                      git@github.com:wmjordan/mupdf.git                                                $# $@
register_remote .                                                             zhiyaluo                                 git@github.com:zhiyaluo/mupdf.git                                                $# $@
register_remote .                                                             zmughal                                  git@github.com:zmughal/mupdf.git                                                 $# $@
register_remote thirdparty/curl                                               ArtifexCorp                              git://git.ghostscript.com/thirdparty-curl.git                                    $# $@
register_remote thirdparty/curl                                               ArtifexSoftware                          git@github.com:ArtifexSoftware/thirdparty-curl.git                               $# $@
register_remote thirdparty/curl                                               artifex-local                            ../../../../tmp/thirdparty-curl/                                                 $# $@
register_remote thirdparty/freeglut                                           ArtifexCorp                              git://git.ghostscript.com/thirdparty-freeglut.git                                $# $@
register_remote thirdparty/freeglut                                           ArtifexSoftware                          git@github.com:ArtifexSoftware/thirdparty-freeglut.git                           $# $@
register_remote thirdparty/freeglut                                           artifex-local                            ../../../../tmp/thirdparty-freeglut/                                             $# $@
register_remote thirdparty/freetype                                           ArtifexCorp                              git://git.ghostscript.com/thirdparty-freetype2.git                               $# $@
register_remote thirdparty/freetype                                           ArtifexSoftware                          git@github.com:ArtifexSoftware/thirdparty-freetype2.git                          $# $@
register_remote thirdparty/freetype                                           artifex-local                            ../../../../tmp/thirdparty-freetype2/                                            $# $@
register_remote thirdparty/harfbuzz                                           Acidburn0zzz                             git@github.com:Acidburn0zzz/harfbuzz.git                                         $# $@
register_remote thirdparty/harfbuzz                                           Adenilson                                git@github.com:Adenilson/harfbuzz.git                                            $# $@
register_remote thirdparty/harfbuzz                                           ArtifexCorp                              git://git.ghostscript.com/thirdparty-harfbuzz.git                                $# $@
register_remote thirdparty/harfbuzz                                           ArtifexSoftware                          git@github.com:ArtifexSoftware/thirdparty-harfbuzz.git                           $# $@
register_remote thirdparty/harfbuzz                                           Daeren                                   git@github.com:Daeren/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           DigitalKhatt                             git@github.com:DigitalKhatt/harfbuzz.git                                         $# $@
register_remote thirdparty/harfbuzz                                           GaryQian                                 git@github.com:GaryQian/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           Ghabry                                   git@github.com:Ghabry/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           HalCanary                                git@github.com:HalCanary/harfbuzz.git                                            $# $@
register_remote thirdparty/harfbuzz                                           HinTak                                   git@github.com:HinTak/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           KindDragon                               git@github.com:KindDragon/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           Phaiax                                   git@github.com:Phaiax/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           RazrFalcon                               git@github.com:RazrFalcon/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           ShiftMediaProject                        git@github.com:ShiftMediaProject/harfbuzz.git                                    $# $@
register_remote thirdparty/harfbuzz                                           SimonSapin                               git@github.com:SimonSapin/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           TypesettingTools                         git@github.com:TypesettingTools/harfbuzz.git                                     $# $@
register_remote thirdparty/harfbuzz                                           VincentWei                               git@github.com:VincentWei/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           adrianwong                               git@github.com:adrianwong/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           anthrotype                               git@github.com:anthrotype/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           artifex-local                            ../../../../tmp/thirdparty-harfbuzz/                                             $# $@
register_remote thirdparty/harfbuzz                                           attente                                  git@github.com:attente/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           autofetch                                git@github.com:autofetch/harfbuzz.git                                            $# $@
register_remote thirdparty/harfbuzz                                           blino                                    git@github.com:blino/harfbuzz.git                                                $# $@
register_remote thirdparty/harfbuzz                                           brawer                                   git@github.com:brawer/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           buckaroo-pm                              git@github.com:buckaroo-pm/harfbuzz.git                                          $# $@
register_remote thirdparty/harfbuzz                                           buckaroo-upgrade-bot                     git@github.com:buckaroo-upgrade-bot/harfbuzz.git                                 $# $@
register_remote thirdparty/harfbuzz                                           bungeman                                 git@github.com:bungeman/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           cclauss                                  git@github.com:cclauss/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           chouquette                               git@github.com:chouquette/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           ckitagawa-work                           git@github.com:ckitagawa-work/harfbuzz.git                                       $# $@
register_remote thirdparty/harfbuzz                                           cpeterso                                 git@github.com:cpeterso/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           darktohka                                git@github.com:darktohka/harfbuzz.git                                            $# $@
register_remote thirdparty/harfbuzz                                           dmoody256                                git@github.com:dmoody256/harfbuzz-1.git                                          $# $@
register_remote thirdparty/harfbuzz                                           domschl                                  git@github.com:domschl/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           donny-dont                               git@github.com:donny-dont/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           drott                                    git@github.com:drott/harfbuzz.git                                                $# $@
register_remote thirdparty/harfbuzz                                           eaenet                                   git@github.com:eaenet/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           ebraminio                                git@github.com:ebraminio/harfbuzz.git                                            $# $@
register_remote thirdparty/harfbuzz                                           ekmett                                   git@github.com:ekmett/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           emuller-amazon                           git@github.com:emuller-amazon/harfbuzz.git                                       $# $@
register_remote thirdparty/harfbuzz                                           epico                                    git@github.com:epico/harfbuzz.git                                                $# $@
register_remote thirdparty/harfbuzz                                           fanc999                                  git@github.com:fanc999/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           filippos-lagopoulos                      git@github.com:filippos-lagopoulos/harfbuzz.git                                  $# $@
register_remote thirdparty/harfbuzz                                           fred-wang                                git@github.com:fred-wang/harfbuzz.git                                            $# $@
register_remote thirdparty/harfbuzz                                           garretrieger                             git@github.com:garretrieger/harfbuzz.git                                         $# $@
register_remote thirdparty/harfbuzz                                           gideros                                  git@github.com:gideros/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           givia                                    git@github.com:givia/harfbuzz.git                                                $# $@
register_remote thirdparty/harfbuzz                                           googlefonts                              git@github.com:googlefonts/harfbuzz.git                                          $# $@
register_remote thirdparty/harfbuzz                                           guillaumemillot                          git@github.com:guillaumemillot/harfbuzz.git                                      $# $@
register_remote thirdparty/harfbuzz                                           gvictor                                  git@github.com:gvictor/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           harfbuzz                                 git@github.com:harfbuzz/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           hfhchan                                  git@github.com:hfhchan/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           hunter-packages                          git@github.com:hunter-packages/harfbuzz.git                                      $# $@
register_remote thirdparty/harfbuzz                                           imgtec                                   git@github.com:imgtec/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           jameshilliard                            git@github.com:jameshilliard/harfbuzz.git                                        $# $@
register_remote thirdparty/harfbuzz                                           jgranick                                 git@github.com:jgranick/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           jrlanglois                               git@github.com:jrlanglois/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           kant                                     git@github.com:kant/harfbuzz.git                                                 $# $@
register_remote thirdparty/harfbuzz                                           kbrow1i                                  git@github.com:kbrow1i/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           khaledhosny                              git@github.com:khaledhosny/harfbuzz.git                                          $# $@
register_remote thirdparty/harfbuzz                                           kojiishi                                 git@github.com:kojiishi/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           lantw44                                  git@github.com:lantw44/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           lazka                                    git@github.com:lazka/harfbuzz.git                                                $# $@
register_remote thirdparty/harfbuzz                                           lionel-                                  git@github.com:lionel-/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           litherum                                 git@github.com:litherum/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           m0hamed                                  git@github.com:m0hamed/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           maksqwe                                  git@github.com:maksqwe/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           mapycz                                   git@github.com:mapycz/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           marklh9                                  git@github.com:marklh9/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           mathstuf                                 git@github.com:mathstuf/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           mbutterick                               git@github.com:mbutterick/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           mhosken                                  git@github.com:mhosken/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           mistydemeo                               git@github.com:mistydemeo/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           molind                                   git@github.com:molind/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           mortentor                                git@github.com:mortentor/harfbuzz.git                                            $# $@
register_remote thirdparty/harfbuzz                                           moyogo                                   git@github.com:moyogo/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           n8willis                                 git@github.com:n8willis/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           patrickyoui                              git@github.com:patrickyoui/harfbuzz.git                                          $# $@
register_remote thirdparty/harfbuzz                                           planteen                                 git@github.com:planteen/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           prrace                                   git@github.com:prrace/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           punchcutter                              git@github.com:punchcutter/harfbuzz.git                                          $# $@
register_remote thirdparty/harfbuzz                                           radwave                                  git@github.com:radwave/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           rdb                                      git@github.com:rdb/harfbuzz.git                                                  $# $@
register_remote thirdparty/harfbuzz                                           ricotz                                   git@github.com:ricotz/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           rig-project                              git@github.com:rig-project/harfbuzz.git                                          $# $@
register_remote thirdparty/harfbuzz                                           rossburton                               git@github.com:rossburton/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           rouabdelkader-gpsw                       git@github.com:rouabdelkader-gpsw/harfbuzz.git                                   $# $@
register_remote thirdparty/harfbuzz                                           roubert                                  git@github.com:roubert/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           rsheeter                                 git@github.com:rsheeter/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           ryandesign                               git@github.com:ryandesign/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           sebras                                   git@github.com:sebras/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           simoncozens                              git@github.com:simoncozens/harfbuzz.git                                          $# $@
register_remote thirdparty/harfbuzz                                           simonis                                  git@github.com:simonis/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           spl                                      git@github.com:spl/harfbuzz.git                                                  $# $@
register_remote thirdparty/harfbuzz                                           stbergmann                               git@github.com:stbergmann/harfbuzz.git                                           $# $@
register_remote thirdparty/harfbuzz                                           stooke                                   git@github.com:stooke/harfbuzz.git                                               $# $@
register_remote thirdparty/harfbuzz                                           torarnv                                  git@github.com:torarnv/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           tp-m                                     git@github.com:tp-m/harfbuzz.git                                                 $# $@
register_remote thirdparty/harfbuzz                                           tronical                                 git@github.com:tronical/harfbuzz.git                                             $# $@
register_remote thirdparty/harfbuzz                                           vkrause                                  git@github.com:vkrause/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           waywardmonkeys                           git@github.com:waywardmonkeys/harfbuzz.git                                       $# $@
register_remote thirdparty/harfbuzz                                           zauguin                                  git@github.com:zauguin/harfbuzz.git                                              $# $@
register_remote thirdparty/harfbuzz                                           zillemarco                               git@github.com:zillemarco/harfbuzz.git                                           $# $@
register_remote thirdparty/jbig2dec                                           ArtifexCorp                              git://git.ghostscript.com/jbig2dec.git                                           $# $@
register_remote thirdparty/jbig2dec                                           ArtifexSoftware                          git@github.com:ArtifexSoftware/jbig2dec.git                                      $# $@
register_remote thirdparty/jbig2dec                                           artifex-local                            ../../../../tmp/jbig2dec/                                                        $# $@
register_remote thirdparty/lcms2                                              ArtifexCorp                              git://git.ghostscript.com/thirdparty-lcms2.git                                   $# $@
register_remote thirdparty/lcms2                                              ArtifexSoftware                          git@github.com:ArtifexSoftware/thirdparty-lcms2.git                              $# $@
register_remote thirdparty/lcms2                                              artifex-local                            ../../../../tmp/thirdparty-lcms2/                                                $# $@
register_remote thirdparty/libjpeg                                            ArtifexCorp                              git://git.ghostscript.com/thirdparty-libjpeg.git                                 $# $@
register_remote thirdparty/libjpeg                                            ArtifexSoftware                          git@github.com:ArtifexSoftware/thirdparty-libjpeg.git                            $# $@
register_remote thirdparty/libjpeg                                            artifex-local                            ../../../../tmp/thirdparty-libjpeg/                                              $# $@
register_remote thirdparty/mujs                                               ArtifexCorp                              git://git.ghostscript.com/mujs.git                                               $# $@
register_remote thirdparty/mujs                                               ArtifexSoftware                          git@github.com:ArtifexSoftware/mujs.git                                          $# $@
register_remote thirdparty/mujs                                               Frankie-PellesC                          git@github.com:Frankie-PellesC/mujs.git                                          $# $@
register_remote thirdparty/mujs                                               LonghronShen                             git@github.com:LonghronShen/mujs.git                                             $# $@
register_remote thirdparty/mujs                                               Torccxvii                                git@github.com:ccxvii/mujs.git                                                   $# $@
register_remote thirdparty/mujs                                               artifex-local                            ../../../../tmp/mujs/                                                            $# $@
register_remote thirdparty/mujs                                               aseprite                                 git@github.com:aseprite/mujs.git                                                 $# $@
register_remote thirdparty/mujs                                               avih                                     git@github.com:avih/mujs.git                                                     $# $@
register_remote thirdparty/mujs                                               buckaroo-pm                              git@github.com:buckaroo-pm/mujs.git                                              $# $@
register_remote thirdparty/mujs                                               ccxvii                                   git@github.com:ccxvii/mujs.git                                                   $# $@
register_remote thirdparty/mujs                                               ezio3593                                 git@github.com:ezio3593/mujs.git                                                 $# $@
register_remote thirdparty/mujs                                               hbp                                      git@github.com:hbp/mujs.git                                                      $# $@
register_remote thirdparty/mujs                                               hean01                                   git@github.com:hean01/mujs.git                                                   $# $@
register_remote thirdparty/mujs                                               isRyven                                  git@github.com:isRyven/mujs.git                                                  $# $@
register_remote thirdparty/mujs                                               katlogic                                 git@github.com:katlogic/mujs.git                                                 $# $@
register_remote thirdparty/mujs                                               liangyaozhan                             git@github.com:liangyaozhan/mujs.git                                             $# $@
register_remote thirdparty/mujs                                               monstersb                                git@github.com:monstersb/mujs.git                                                $# $@
register_remote thirdparty/mujs                                               njlr                                     git@github.com:njlr/mujs.git                                                     $# $@
register_remote thirdparty/mujs                                               vaporstack                               git@github.com:vaporstack/mujs.git                                               $# $@
register_remote thirdparty/mujs                                               weimingtom                               git@github.com:weimingtom/mujs.git                                               $# $@
register_remote thirdparty/mujs                                               wxd237                                   git@github.com:wxd237/mujs.git                                                   $# $@
register_remote thirdparty/mujs                                               yurivict                                 git@github.com:yurivict/mujs.git                                                 $# $@
register_remote thirdparty/mujs                                               yzwduck                                  git@github.com:yzwduck/mujs.git                                                  $# $@
register_remote thirdparty/openjpeg                                           ArtifexCorp                              git://git.ghostscript.com/thirdparty-openjpeg.git                                $# $@
register_remote thirdparty/openjpeg                                           ArtifexSoftware                          git@github.com:ArtifexSoftware/thirdparty-openjpeg.git                           $# $@
register_remote thirdparty/openjpeg                                           artifex-local                            ../../../../tmp/thirdparty-openjpeg/                                             $# $@
register_remote thirdparty/zlib                                               ArtifexCorp                              git://git.ghostscript.com/thirdparty-zlib.git                                    $# $@
register_remote thirdparty/zlib                                               ArtifexSoftware                          git@github.com:ArtifexSoftware/thirdparty-zlib.git                               $# $@
register_remote thirdparty/zlib                                               artifex-local                            ../../../../tmp/thirdparty-zlib/                                                 $# $@



popd                                                                            2> /dev/null   > /dev/null

