/*
 * NEVER EVER edit this manually, fix the mkhelp.pl script instead!
 */

#include "tool_hugehelp.h"

#ifdef USE_MANUAL

void hugehelp(void)
{
   fputs(
"                                  _   _ ____  _\n"
"  Project                     ___| | | |  _ \\| |\n"
"                             / __| | | | |_) | |\n"
"                            | (__| |_| |  _ <| |___\n"
"                             \\___|\\___/|_| \\_\\_____|\n"
"# curl tutorial\n"
"## Simple Usage\n"
"\n"
"Get the main page from a web-server:\n"
"\n"
"    curl https://www.example.com/\n"
"\n"
"Get a README file from an FTP server:\n"
"\n"
"    curl ftp://ftp.example.com/README\n"
"\n"
"Get a web page from a server using port 8000:\n"
"\n"
, stdout);
 fputs(
"    curl http://www.example.com:8000/\n"
"\n"
"Get a directory listing of an FTP site:\n"
"\n"
"    curl ftp://ftp.example.com/\n"
"\n"
"Get the all terms matching curl from a dictionary:\n"
"\n"
"    curl dict://dict.example.com/m:curl\n"
"\n"
"Get the definition of curl from a dictionary:\n"
"\n"
"    curl dict://dict.example.com/d:curl\n"
"\n"
"Fetch two documents at once:\n"
"\n"
"    curl ftp://ftp.example.com/ http://www.example.com:8000/\n"
"\n"
"Get a file off an FTPS server:\n"
"\n"
"    curl ftps://files.are.example.com/secrets.txt\n"
"\n"
, stdout);
 fputs(
"or use the more appropriate FTPS way to get the same file:\n"
"\n"
"    curl --ftp-ssl ftp://files.are.example.com/secrets.txt\n"
"\n"
"Get a file from an SSH server using SFTP:\n"
"\n"
"    curl -u username sftp://example.com/etc/issue\n"
"\n"
"Get a file from an SSH server using SCP using a private key (not\n"
"password-protected) to authenticate:\n"
"\n"
"    curl -u username: --key ~/.ssh/id_rsa scp://example.com/~/file.txt\n"
"\n"
"Get a file from an SSH server using SCP using a private key\n"
"(password-protected) to authenticate:\n"
"\n"
, stdout);
 fputs(
"    curl -u username: --key ~/.ssh/id_rsa --pass private_key_password\n"
"    scp://example.com/~/file.txt\n"
"\n"
"Get the main page from an IPv6 web server:\n"
"\n"
"    curl \"http://[2001:1890:1112:1::20]/\"\n"
"\n"
"Get a file from an SMB server:\n"
"\n"
"    curl -u \"domain\\username:passwd\" smb://server.example.com/share/file.txt\n"
"\n"
"## Download to a File\n"
"\n"
"Get a web page and store in a local file with a specific name:\n"
"\n"
"    curl -o thatpage.html http://www.example.com/\n"
"\n"
, stdout);
 fputs(
"Get a web page and store in a local file, make the local file get the name of\n"
"the remote document (if no file name part is specified in the URL, this will\n"
"fail):\n"
"\n"
"    curl -O http://www.example.com/index.html\n"
"\n"
"Fetch two files and store them with their remote names:\n"
"\n"
"    curl -O www.haxx.se/index.html -O curl.se/download.html\n"
"\n"
"## Using Passwords\n"
"\n"
"### FTP\n"
"\n"
"To ftp files using name and password, include them in the URL like:\n"
"\n"
"    curl ftp://name:passwd@ftp.server.example:port/full/path/to/file\n"
"\n"
, stdout);
 fputs(
"or specify them with the `-u` flag like\n"
"\n"
"    curl -u name:passwd ftp://ftp.server.example:port/full/path/to/file\n"
"\n"
"### FTPS\n"
"\n"
"It is just like for FTP, but you may also want to specify and use SSL-specific\n"
"options for certificates etc.\n"
"\n"
"Note that using `FTPS://` as prefix is the *implicit* way as described in the\n"
"standards while the recommended *explicit* way is done by using `FTP://` and\n"
"the `--ssl-reqd` option.\n"
"\n"
"### SFTP / SCP\n"
"\n"
, stdout);
 fputs(
"This is similar to FTP, but you can use the `--key` option to specify a\n"
"private key to use instead of a password. Note that the private key may itself\n"
"be protected by a password that is unrelated to the login password of the\n"
"remote system; this password is specified using the `--pass` option.\n"
"Typically, curl will automatically extract the public key from the private key\n"
"file, but in cases where curl does not have the proper library support, a\n"
, stdout);
 fputs(
"matching public key file must be specified using the `--pubkey` option.\n"
"\n"
"### HTTP\n"
"\n"
"like:\n"
"\n"
"    curl http://name:passwd@http.server.example/full/path/to/file\n"
"\n"
"or specify user and password separately like in\n"
"\n"
"    curl -u name:passwd http://http.server.example/full/path/to/file\n"
"\n"
"HTTP offers many different methods of authentication and curl supports\n"
"several: Basic, Digest, NTLM and Negotiate (SPNEGO). Without telling which\n"
"method to use, curl defaults to Basic. You can also ask curl to pick the most\n"
, stdout);
 fputs(
"secure ones out of the ones that the server accepts for the given URL, by\n"
"using `--anyauth`.\n"
"\n"
"**Note**! According to the URL specification, HTTP URLs can not contain a user\n"
"and password, so that style will not work when using curl via a proxy, even\n"
"though curl allows it at other times. When using a proxy, you _must_ use the\n"
"`-u` style for user and password.\n"
"\n"
"### HTTPS\n"
"\n"
"Probably most commonly used with private certificates, as explained below.\n"
"\n"
"## Proxy\n"
"\n"
, stdout);
 fputs(
"It does not have special support for FTP proxy servers since there are no\n"
"standards for those, but it can still be made to work with many of them. You\n"
"can also use both HTTP and SOCKS proxies to transfer files to and from FTP\n"
"servers.\n"
"\n"
"Get an ftp file using an HTTP proxy named my-proxy that uses port 888:\n"
"\n"
"    curl -x my-proxy:888 ftp://ftp.example.com/README\n"
"\n"
"Get a file from an HTTP server that requires user and password, using the\n"
"same proxy as above:\n"
"\n"
, stdout);
 fputs(
"    curl -u user:passwd -x my-proxy:888 http://www.example.com/\n"
"\n"
"Some proxies require special authentication. Specify by using -U as above:\n"
"\n"
"    curl -U user:passwd -x my-proxy:888 http://www.example.com/\n"
"\n"
"A comma-separated list of hosts and domains which do not use the proxy can be\n"
"specified as:\n"
"\n"
"    curl --noproxy example.com -x my-proxy:888 http://www.example.com/\n"
"\n"
"If the proxy is specified with `--proxy1.0` instead of `--proxy` or `-x`, then\n"
"\n"
, stdout);
 fputs(
"See also the environment variables Curl supports that offer further proxy\n"
"control.\n"
"\n"
"Most FTP proxy servers are set up to appear as a normal FTP server from the\n"
"client's perspective, with special commands to select the remote FTP server.\n"
"\n"
"set up transfers through many FTP proxies. For example, a file can be uploaded\n"
"to a remote FTP server using a Blue Coat FTP proxy with the options:\n"
"\n"
"    curl -u \"username@ftp.server.example Proxy-Username:Remote-Pass\"\n"
, stdout);
 fputs(
"      --ftp-account Proxy-Password --upload-file local-file\n"
"      ftp://my-ftp.proxy.example:21/remote/upload/path/\n"
"\n"
"See the manual for your FTP proxy to determine the form it expects to set up\n"
"transfers, and curl's `-v` option to see exactly what curl is sending.\n"
"\n"
"## Piping\n"
"\n"
"Get a key file and add it with `apt-key` (when on a system that uses `apt` for\n"
"package management):\n"
"\n"
"    curl -L https://apt.example.org/llvm-snapshot.gpg.key | sudo apt-key add -\n"
"\n"
, stdout);
 fputs(
"The '|' pipes the output to STDIN. `-` tells `apt-key` that the key file\n"
"should be read from STDIN.\n"
"\n"
"## Ranges\n"
"\n"
"HTTP 1.1 introduced byte-ranges. Using this, a client can request to get only\n"
"one or more sub-parts of a specified document. Curl supports this with the\n"
"`-r` flag.\n"
"\n"
"Get the first 100 bytes of a document:\n"
"\n"
"    curl -r 0-99 http://www.example.com/\n"
"\n"
"Get the last 500 bytes of a document:\n"
"\n"
"    curl -r -500 http://www.example.com/\n"
"\n"
"specify start and stop position.\n"
"\n"
, stdout);
 fputs(
"Get the first 100 bytes of a document using FTP:\n"
"\n"
"    curl -r 0-99 ftp://www.example.com/README\n"
"\n"
"## Uploading\n"
"\n"
"### FTP / FTPS / SFTP / SCP\n"
"\n"
"Upload all data on stdin to a specified server:\n"
"\n"
"    curl -T - ftp://ftp.example.com/myfile\n"
"\n"
"Upload data from a specified file, login with user and password:\n"
"\n"
"    curl -T uploadfile -u user:passwd ftp://ftp.example.com/myfile\n"
"\n"
"Upload a local file to the remote site, and use the local file name at the\n"
"remote site too:\n"
"\n"
, stdout);
 fputs(
"    curl -T uploadfile -u user:passwd ftp://ftp.example.com/\n"
"\n"
"Upload a local file to get appended to the remote file:\n"
"\n"
"    curl -T localfile -a ftp://ftp.example.com/remotefile\n"
"\n"
"configured to allow that kind of tunneling. If it does, you can run curl in a\n"
"fashion similar to:\n"
"\n"
"    curl --proxytunnel -x proxy:port -T localfile ftp.example.com\n"
"\n"
"### SMB / SMBS\n"
"\n"
"    curl -T file.txt -u \"domain\\username:passwd\"\n"
"      smb://server.example.com/share/\n"
"\n"
"### HTTP\n"
"\n"
, stdout);
 fputs(
"Upload all data on stdin to a specified HTTP site:\n"
"\n"
"    curl -T - http://www.example.com/myfile\n"
"\n"
"Note that the HTTP server must have been configured to accept PUT before this\n"
"can be done successfully.\n"
"\n"
"For other ways to do HTTP data upload, see the POST section below.\n"
"\n"
"## Verbose / Debug\n"
"\n"
"If curl fails where it is not supposed to, if the servers do not let you in, if\n"
"you cannot understand the responses: use the `-v` flag to get verbose\n"
, stdout);
 fputs(
"fetching. Curl will output lots of info and what it sends and receives in\n"
"order to let the user see all client-server interaction (but it will not show you\n"
"the actual data).\n"
"\n"
"    curl -v ftp://ftp.example.com/\n"
"\n"
"To get even more details and information on what curl does, try using the\n"
"`--trace` or `--trace-ascii` options with a given file name to log to, like\n"
"this:\n"
"\n"
"    curl --trace trace.txt www.haxx.se\n"
"\n"
"## Detailed Information\n"
"\n"
, stdout);
 fputs(
"Different protocols provide different ways of getting detailed information\n"
"about specific files/documents. To get curl to show detailed information about\n"
"a single file, you should use `-I`/`--head` option. It displays all available\n"
"info on a single file for HTTP and FTP. The HTTP information is a lot more\n"
"extensive.\n"
"\n"
"For HTTP, you can get the header information (the same as `-I` would show)\n"
"shown before the data by using `-i`/`--include`. Curl understands the\n"
, stdout);
 fputs(
"`-D`/`--dump-header` option when getting files from both FTP and HTTP, and it\n"
"will then store the headers in the specified file.\n"
"\n"
"Store the HTTP headers in a separate file (headers.txt in the example):\n"
"\n"
"      curl --dump-header headers.txt curl.se\n"
"\n"
"Note that headers stored in a separate file can be useful at a later time if\n"
"you want curl to use cookies sent by the server. More about that in the\n"
"cookies section.\n"
"\n"
"## POST (HTTP)\n"
"\n"
, stdout);
 fputs(
"It is easy to post data using curl. This is done using the `-d <data>` option.\n"
"The post data must be urlencoded.\n"
"\n"
"Post a simple `name` and `phone` guestbook.\n"
"\n"
"    curl -d \"name=Rafael%20Sagula&phone=3320780\" http://www.example.com/guest.cgi\n"
"\n"
"Or automatically [URL encode the data](https://everything.curl.dev/http/post/url-encode).\n"
"    curl --data-urlencode \"name=Rafael Sagula&phone=3320780\" http://www.example.com/guest.cgi\n"
"\n"
"How to post a form with curl, lesson #1:\n"
"\n"
, stdout);
 fputs(
"Dig out all the `<input>` tags in the form that you want to fill in.\n"
"\n"
"If there is a normal post, you use `-d` to post. `-d` takes a full post\n"
"string, which is in the format\n"
"\n"
"    <variable1>=<data1>&<variable2>=<data2>&...\n"
"\n"
"The variable names are the names set with `\"name=\"` in the `<input>` tags, and\n"
"the data is the contents you want to fill in for the inputs. The data *must*\n"
"be properly URL encoded. That means you replace space with + and that you\n"
, stdout);
 fputs(
"replace weird letters with `%XX` where `XX` is the hexadecimal representation\n"
"of the letter's ASCII code.\n"
"\n"
"Example:\n"
"\n"
"(say if `http://example.com` had the following html)\n"
"\n"
"```html\n"
"<form action=\"post.cgi\" method=\"post\">\n"
"  <input name=user size=10>\n"
"  <input name=pass type=password size=10>\n"
"  <input name=id type=hidden value=\"blablabla\">\n"
"  <input name=ding value=\"submit\">\n"
"</form>\n"
"```\n"
"\n"
"We want to enter user `foobar` with password `12345`.\n"
"\n"
"To post to this, you would enter a curl command line like:\n"
"\n"
, stdout);
 fputs(
"    curl -d \"user=foobar&pass=12345&id=blablabla&ding=submit\" http://example.com/post.cgi\n"
"\n"
"While `-d` uses the application/x-www-form-urlencoded mime-type, generally\n"
"understood by CGI's and similar, curl also supports the more capable\n"
"multipart/form-data type. This latter type supports things like file upload.\n"
"\n"
"`-F` accepts parameters like `-F \"name=contents\"`. If you want the contents to\n"
"be read from a file, use `@filename` as contents. When specifying a file, you\n"
, stdout);
 fputs(
"can also specify the file content type by appending `;type=<mime type>` to the\n"
"file name. You can also post the contents of several files in one field.  For\n"
"example, the field name `coolfiles` is used to send three files, with\n"
"different content types using the following syntax:\n"
"\n"
"    curl -F \"coolfiles=@fil1.gif;type=image/gif,fil2.txt,fil3.html\"\n"
"      http://www.example.com/postit.cgi\n"
"\n"
"If the content-type is not specified, curl will try to guess from the file\n"
, stdout);
 fputs(
"extension (it only knows a few), or use the previously specified type (from an\n"
"earlier file if several files are specified in a list) or else it will use the\n"
"default type `application/octet-stream`.\n"
"\n"
"Emulate a fill-in form with `-F`. Let's say you fill in three fields in a\n"
"form. One field is a file name which to post, one field is your name and one\n"
"field is a file description. We want to post the file we have written named\n"
"`cooltext.txt`. To let curl do the posting of this data instead of your\n"
, stdout);
 fputs(
"favorite browser, you have to read the HTML source of the form page and find\n"
"the names of the input fields. In our example, the input field names are\n"
"`file`, `yourname` and `filedescription`.\n"
"\n"
"    curl -F \"file=@cooltext.txt\" -F \"yourname=Daniel\"\n"
"      -F \"filedescription=Cool text file with cool text inside\"\n"
"      http://www.example.com/postit.cgi\n"
"\n"
"To send two files in one post you can do it in two ways:\n"
"\n"
"Send multiple files in a single field with a single field name:\n"
"\n"
, stdout);
 fputs(
"    curl -F \"pictures=@dog.gif,cat.gif\" $URL\n"
"\n"
"Send two fields with two field names\n"
"\n"
"    curl -F \"docpicture=@dog.gif\" -F \"catpicture=@cat.gif\" $URL\n"
"\n"
"To send a field value literally without interpreting a leading `@` or `<`, or\n"
"an embedded `;type=`, use `--form-string` instead of `-F`. This is recommended\n"
"when the value is obtained from a user or some other unpredictable\n"
"source. Under these circumstances, using `-F` instead of `--form-string` could\n"
, stdout);
 fputs(
"allow a user to trick curl into uploading a file.\n"
"\n"
"## Referrer\n"
"\n"
"An HTTP request has the option to include information about which address\n"
"referred it to the actual page. curl allows you to specify the referrer to be\n"
"used on the command line. It is especially useful to fool or trick stupid\n"
"servers or CGI scripts that rely on that information being available or\n"
"contain certain data.\n"
"\n"
"    curl -e www.exomaple.org http://www.example.com/\n"
"\n"
"## User Agent\n"
"\n"
, stdout);
 fputs(
"An HTTP request has the option to include information about the browser that\n"
"generated the request. Curl allows it to be specified on the command line. It\n"
"is especially useful to fool or trick stupid servers or CGI scripts that only\n"
"accept certain browsers.\n"
"\n"
"Example:\n"
"\n"
"    curl -A 'Mozilla/3.0 (Win95; I)' http://www.bank.example.com/\n"
"\n"
"Other common strings:\n"
"\n"
"- `Mozilla/3.0 (Win95; I)` - Netscape Version 3 for Windows 95\n"
"- `Mozilla/3.04 (Win95; U)` - Netscape Version 3 for Windows 95\n"
, stdout);
 fputs(
"- `Mozilla/2.02 (OS/2; U)` - Netscape Version 2 for OS/2\n"
"- `Mozilla/4.04 [en] (X11; U; AIX 4.2; Nav)` - Netscape for AIX\n"
"- `Mozilla/4.05 [en] (X11; U; Linux 2.0.32 i586)` - Netscape for Linux\n"
"\n"
"Note that Internet Explorer tries hard to be compatible in every way:\n"
"\n"
"- `Mozilla/4.0 (compatible; MSIE 4.01; Windows 95)` - MSIE for W95\n"
"\n"
"Mozilla is not the only possible User-Agent name:\n"
"\n"
"- `Konqueror/1.0` - KDE File Manager desktop client\n"
"- `Lynx/2.7.1 libwww-FM/2.14` - Lynx command line browser\n"
"\n"
, stdout);
 fputs(
"## Cookies\n"
"\n"
"Cookies are generally used by web servers to keep state information at the\n"
"client's side. The server sets cookies by sending a response line in the\n"
"headers that looks like `Set-Cookie: <data>` where the data part then\n"
"typically contains a set of `NAME=VALUE` pairs (separated by semicolons `;`\n"
"like `NAME1=VALUE1; NAME2=VALUE2;`). The server can also specify for what path\n"
"the cookie should be used for (by specifying `path=value`), when the cookie\n"
, stdout);
 fputs(
"should expire (`expire=DATE`), for what domain to use it (`domain=NAME`) and\n"
"if it should be used on secure connections only (`secure`).\n"
"\n"
"If you have received a page from a server that contains a header like:\n"
"\n"
"```http\n"
"Set-Cookie: sessionid=boo123; path=\"/foo\";\n"
"```\n"
"\n"
"it means the server wants that first pair passed on when we get anything in a\n"
"path beginning with `/foo`.\n"
"\n"
"Example, get a page that wants my name passed in a cookie:\n"
"\n"
"    curl -b \"name=Daniel\" www.example.com\n"
"\n"
, stdout);
 fputs(
"sessions. If you get cookies from a server and store them in a file in a\n"
"manner similar to:\n"
"\n"
"    curl --dump-header headers www.example.com\n"
"\n"
"... you can then in a second connect to that (or another) site, use the\n"
"cookies from the `headers.txt` file like:\n"
"\n"
"    curl -b headers.txt www.example.com\n"
"\n"
"While saving headers to a file is a working way to store cookies, it is\n"
"however error-prone and not the preferred way to do this. Instead, make curl\n"
, stdout);
 fputs(
"save the incoming cookies using the well-known Netscape cookie format like\n"
"this:\n"
"\n"
"    curl -c cookies.txt www.example.com\n"
"\n"
"Note that by specifying `-b` you enable the cookie engine and with `-L` you\n"
"can make curl follow a `location:` (which often is used in combination with\n"
"cookies). If a site sends cookies and a location field, you can use a\n"
"non-existing file to trigger the cookie awareness like:\n"
"\n"
"    curl -L -b empty.txt www.example.com\n"
"\n"
, stdout);
 fputs(
"The file to read cookies from must be formatted using plain HTTP headers OR as\n"
"Netscape's cookie file. Curl will determine what kind it is based on the file\n"
"contents. In the above command, curl will parse the header and store the\n"
"cookies received from www.example.com. curl will send to the server the stored\n"
"cookies which match the request as it follows the location. The file\n"
"`empty.txt` may be a nonexistent file.\n"
"\n"
"To read and write cookies from a Netscape cookie file, you can set both `-b`\n"
, stdout);
 fputs(
"and `-c` to use the same file:\n"
"\n"
"    curl -b cookies.txt -c cookies.txt www.example.com\n"
"\n"
"## Progress Meter\n"
"\n"
"The progress meter exists to show a user that something actually is\n"
"happening. The different fields in the output have the following meaning:\n"
"\n"
"    % Total    % Received % Xferd  Average Speed          Time             Curr.\n"
"                                   Dload  Upload Total    Current  Left    Speed\n"
"    0  151M    0 38608    0     0   9406      0  4:41:43  0:00:04  4:41:39  9287\n"
"\n"
, stdout);
 fputs(
"From left-to-right:\n"
"\n"
" - `%`           - percentage completed of the whole transfer\n"
" - `Total`       - total size of the whole expected transfer\n"
" - `%`           - percentage completed of the download\n"
" - `Received`    - currently downloaded amount of bytes\n"
" - `%`           - percentage completed of the upload\n"
" - `Xferd`       - currently uploaded amount of bytes\n"
" - `Average Speed Dload` - the average transfer speed of the download\n"
, stdout);
 fputs(
" - `Average Speed Upload` - the average transfer speed of the upload\n"
" - `Time Total`  - expected time to complete the operation\n"
" - `Time Current` - time passed since the invoke\n"
" - `Time Left`   - expected time left to completion\n"
" - `Curr.Speed`  - the average transfer speed the last 5 seconds (the first\n"
"                   5 seconds of a transfer is based on less time of course.)\n"
"\n"
"The `-#` option will display a totally different progress bar that does not\n"
"need much explanation!\n"
"\n"
"## Speed Limit\n"
"\n"
, stdout);
 fputs(
"let the transfer keep going. By using the switch `-y` and `-Y` you can make\n"
"\n"
"for a specified time.\n"
"\n"
"To have curl abort the download if the speed is slower than 3000 bytes per\n"
"second for 1 minute, run:\n"
"\n"
"    curl -Y 3000 -y 60 www.far-away.example.com\n"
"\n"
"This can be used in combination with the overall time limit, so that the above\n"
"operation must be completed in whole within 30 minutes:\n"
"\n"
"    curl -m 1800 -Y 3000 -y 60 www.far-away.example.com\n"
"\n"
, stdout);
 fputs(
"Forcing curl not to transfer data faster than a given rate is also possible,\n"
"which might be useful if you are using a limited bandwidth connection and you\n"
"do not want your transfer to use all of it (sometimes referred to as\n"
"*bandwidth throttle*).\n"
"\n"
"Make curl transfer data no faster than 10 kilobytes per second:\n"
"\n"
"    curl --limit-rate 10K www.far-away.example.com\n"
"\n"
"or\n"
"\n"
"    curl --limit-rate 10240 www.far-away.example.com\n"
"\n"
"Or prevent curl from uploading data faster than 1 megabyte per second:\n"
"\n"
, stdout);
 fputs(
"    curl -T upload --limit-rate 1M ftp://uploads.example.com\n"
"\n"
"When using the `--limit-rate` option, the transfer rate is regulated on a\n"
"per-second basis, which will cause the total transfer speed to become lower\n"
"than the given number. Sometimes of course substantially lower, if your\n"
"transfer stalls during periods.\n"
"\n"
"## Config File\n"
"\n"
"Microsoft Windows systems) from the user's home dir on startup.\n"
"\n"
"The config file could be made up with normal command line switches, but you\n"
, stdout);
 fputs(
"can also specify the long options without the dashes to make it more\n"
"readable. You can separate the options and the parameter with spaces, or with\n"
"`=` or `:`. Comments can be used within the file. If the first letter on a\n"
"line is a `#`-symbol the rest of the line is treated as a comment.\n"
"\n"
"If you want the parameter to contain spaces, you must enclose the entire\n"
"parameter within double quotes (`\"`). Within those quotes, you specify a quote\n"
"as `\\\"`.\n"
"\n"
, stdout);
 fputs(
"NOTE: You must specify options and their arguments on the same line.\n"
"\n"
"Example, set default time out and proxy in a config file:\n"
"\n"
"    # We want a 30 minute timeout:\n"
"    -m 1800\n"
"    # ... and we use a proxy for all accesses:\n"
"    proxy = proxy.our.domain.com:8080\n"
"\n"
"Whitespaces ARE significant at the end of lines, but all whitespace leading\n"
"up to the first characters of each line are ignored.\n"
"\n"
"Prevent curl from reading the default file by using -q as the first command\n"
"line parameter, like:\n"
"\n"
, stdout);
 fputs(
"    curl -q www.example.org\n"
"\n"
"Force curl to get and display a local help page in case it is invoked without\n"
"URL by making a config file similar to:\n"
"\n"
"    # default url to get\n"
"    url = \"http://help.with.curl.example.com/curlhelp.html\"\n"
"\n"
"You can specify another config file to be read by using the `-K`/`--config`\n"
"flag. If you set config file name to `-` it will read the config from stdin,\n"
"which can be handy if you want to hide options from being visible in process\n"
"tables etc:\n"
"\n"
, stdout);
 fputs(
"    echo \"user = user:passwd\" | curl -K - http://that.secret.example.com\n"
"\n"
"## Extra Headers\n"
"\n"
"When using curl in your own programs, you may end up needing to pass on your\n"
"own custom headers when getting a web page. You can do this by using the `-H`\n"
"flag.\n"
"\n"
"Example, send the header `X-you-and-me: yes` to the server when getting a\n"
"page:\n"
"\n"
"    curl -H \"X-you-and-me: yes\" love.example.com\n"
"\n"
"This can also be useful in case you want curl to send a different text in a\n"
, stdout);
 fputs(
"header than it normally does. The `-H` header you specify then replaces the\n"
"header curl would normally send. If you replace an internal header with an\n"
"empty one, you prevent that header from being sent. To prevent the `Host:`\n"
"header from being used:\n"
"\n"
"    curl -H \"Host:\" server.example.com\n"
"\n"
"## FTP and Path Names\n"
"\n"
"Do note that when getting files with a `ftp://` URL, the given path is\n"
"relative to the directory you enter. To get the file `README` from your home\n"
"directory at your ftp site, do:\n"
"\n"
, stdout);
 fputs(
"    curl ftp://user:passwd@my.example.com/README\n"
"\n"
"If you want the README file from the root directory of that same site, you\n"
"need to specify the absolute file name:\n"
"\n"
"    curl ftp://user:passwd@my.example.com//README\n"
"\n"
"(I.e with an extra slash in front of the file name.)\n"
"\n"
"## SFTP and SCP and Path Names\n"
"\n"
"With sftp: and scp: URLs, the path name given is the absolute name on the\n"
"server. To access a file relative to the remote user's home directory, prefix\n"
"the file with `/~/` , such as:\n"
"\n"
, stdout);
 fputs(
"    curl -u $USER sftp://home.example.com/~/.bashrc\n"
"\n"
"## FTP and Firewalls\n"
"\n"
"The FTP protocol requires one of the involved parties to open a second\n"
"connection as soon as data is about to get transferred. There are two ways to\n"
"do this.\n"
"\n"
"The default way for curl is to issue the PASV command which causes the server\n"
"to open another port and await another connection performed by the\n"
"client. This is good if the client is behind a firewall that does not allow\n"
"incoming connections.\n"
"\n"
, stdout);
 fputs(
"    curl ftp.example.com\n"
"\n"
"If the server, for example, is behind a firewall that does not allow\n"
"connections on ports other than 21 (or if it just does not support the `PASV`\n"
"command), the other way to do it is to use the `PORT` command and instruct the\n"
"server to connect to the client on the given IP number and port (as parameters\n"
"to the PORT command).\n"
"\n"
"The `-P` flag to curl supports a few different options. Your machine may have\n"
, stdout);
 fputs(
"several IP-addresses and/or network interfaces and curl allows you to select\n"
"which of them to use. Default address can also be used:\n"
"\n"
"    curl -P - ftp.example.com\n"
"\n"
"Download with `PORT` but use the IP address of our `le0` interface (this does\n"
"not work on Windows):\n"
"\n"
"    curl -P le0 ftp.example.com\n"
"\n"
"Download with `PORT` but use 192.168.0.10 as our IP address to use:\n"
"\n"
"    curl -P 192.168.0.10 ftp.example.com\n"
"\n"
"## Network Interface\n"
"\n"
, stdout);
 fputs(
"Get a web page from a server using a specified port for the interface:\n"
"\n"
"    curl --interface eth0:1 http://www.example.com/\n"
"\n"
"or\n"
"\n"
"    curl --interface 192.168.1.10 http://www.example.com/\n"
"\n"
"## HTTPS\n"
"\n"
"Secure HTTP requires a TLS library to be installed and used when curl is\n"
"built. If that is done, curl is capable of retrieving and posting documents\n"
"using the HTTPS protocol.\n"
"\n"
"Example:\n"
"\n"
"    curl https://secure.example.com\n"
"\n"
"that require valid certificates. The only drawback is that the certificate\n"
, stdout);
 fputs(
"needs to be in PEM-format. PEM is a standard and open format to store\n"
"certificates with, but it is not used by the most commonly used browsers. If\n"
"you want curl to use the certificates you use with your favorite browser, you\n"
"may need to download/compile a converter that can convert your browser's\n"
"formatted certificates to PEM formatted ones.\n"
"\n"
"Example on how to automatically retrieve a document using a certificate with a\n"
"personal password:\n"
"\n"
, stdout);
 fputs(
"    curl -E /path/to/cert.pem:password https://secure.example.com/\n"
"\n"
"If you neglect to specify the password on the command line, you will be\n"
"prompted for the correct password before any data can be received.\n"
"\n"
"Many older HTTPS servers have problems with specific SSL or TLS versions,\n"
"which newer versions of OpenSSL etc use, therefore it is sometimes useful to\n"
"specify what TLS version curl should use.:\n"
"\n"
"    curl --tlv1.0 https://secure.example.com/\n"
"\n"
, stdout);
 fputs(
"Otherwise, curl will attempt to use a sensible TLS default version.\n"
"\n"
"## Resuming File Transfers\n"
"\n"
"To continue a file transfer where it was previously aborted, curl supports\n"
"resume on HTTP(S) downloads as well as FTP uploads and downloads.\n"
"\n"
"Continue downloading a document:\n"
"\n"
"    curl -C - -o file ftp://ftp.example.com/path/file\n"
"\n"
"Continue uploading a document:\n"
"\n"
"    curl -C - -T file ftp://ftp.example.com/path/file\n"
"Continue downloading a document from a web server\n"
"\n"
, stdout);
 fputs(
"    curl -C - -o file http://www.example.com/\n"
"\n"
"## Time Conditions\n"
"\n"
"HTTP allows a client to specify a time condition for the document it requests.\n"
"It is `If-Modified-Since` or `If-Unmodified-Since`. curl allows you to specify\n"
"them with the `-z`/`--time-cond` flag.\n"
"\n"
"For example, you can easily make a download that only gets performed if the\n"
"remote file is newer than a local copy. It would be made like:\n"
"\n"
"    curl -z local.html http://remote.example.com/remote.html\n"
"\n"
, stdout);
 fputs(
"Or you can download a file only if the local file is newer than the remote\n"
"one. Do this by prepending the date string with a `-`, as in:\n"
"\n"
"    curl -z -local.html http://remote.example.com/remote.html\n"
"\n"
"You can specify a plain text date as condition. Tell curl to only download the\n"
"file if it was updated since January 12, 2012:\n"
"\n"
"    curl -z \"Jan 12 2012\" http://remote.example.com/remote.html\n"
"\n"
"other way around by prepending it with a dash (`-`).\n"
"\n"
"## DICT\n"
"\n"
"For fun try\n"
"\n"
, stdout);
 fputs(
"    curl dict://dict.org/m:curl\n"
"    curl dict://dict.org/d:heisenbug:jargon\n"
"    curl dict://dict.org/d:daniel:gcide\n"
"\n"
"Aliases for `m` are `match` and `find`, and aliases for `d` are `define` and\n"
"`lookup`. For example,\n"
"\n"
"    curl dict://dict.org/find:curl\n"
"\n"
"Commands that break the URL description of the RFC (but not the DICT\n"
"protocol) are\n"
"\n"
"    curl dict://dict.org/show:db\n"
"    curl dict://dict.org/show:strat\n"
"\n"
"Authentication support is still missing\n"
"\n"
"## LDAP\n"
"\n"
, stdout);
 fputs(
"If you have installed the OpenLDAP library, curl can take advantage of it and\n"
"offer `ldap://` support. On Windows, curl will use WinLDAP from Platform SDK\n"
"by default.\n"
"\n"
"Default protocol version used by curl is LDAP version 3. Version 2 will be\n"
"used as a fallback mechanism in case version 3 fails to connect.\n"
"LDAP is a complex thing and writing an LDAP query is not an easy\n"
"task. Familiarize yourself with the exact syntax description elsewhere. One\n"
"such place might be: [RFC 2255, The LDAP URL\n"
, stdout);
 fputs(
"Format](https://curl.se/rfc/rfc2255.txt)\n"
"\n"
"To show you an example, this is how to get all people from an LDAP server that\n"
"has a certain subdomain in their email address:\n"
"\n"
"    curl -B \"ldap://ldap.example.com/o=frontec??sub?mail=*sth.example.com\"\n"
"\n"
"You also can use authentication when accessing LDAP catalog:\n"
"\n"
"    curl -u user:passwd \"ldap://ldap.example.com/o=frontec??sub?mail=*\"\n"
"    curl \"ldap://user:passwd@ldap.example.com/o=frontec??sub?mail=*\"\n"
"\n"
, stdout);
 fputs(
"By default, if user and password are provided, OpenLDAP/WinLDAP will use basic\n"
"authentication. On Windows you can control this behavior by providing one of\n"
"`--basic`, `--ntlm` or `--digest` option in curl command line\n"
"\n"
"    curl --ntlm \"ldap://user:passwd@ldap.example.com/o=frontec??sub?mail=*\"\n"
"\n"
"On Windows, if no user/password specified, auto-negotiation mechanism will be\n"
"used with current logon credentials (SSPI/SPNEGO).\n"
"\n"
"## Environment Variables\n"
"\n"
"    http_proxy, HTTPS_PROXY, FTP_PROXY\n"
"\n"
, stdout);
 fputs(
"They should be set for protocol-specific proxies. General proxy should be set\n"
"with\n"
"\n"
"    ALL_PROXY\n"
"\n"
"A comma-separated list of host names that should not go through any proxy is\n"
"set in (only an asterisk, `*` matches all hosts)\n"
"\n"
"    NO_PROXY\n"
"\n"
"If the host name matches one of these strings, or the host is within the\n"
"domain of one of these strings, transactions with that node will not be done\n"
"over proxy. When a domain is used, it needs to start with a period. A user can\n"
, stdout);
 fputs(
"specify that both www.example.com and foo.example.com should not use a proxy\n"
"by setting `NO_PROXY` to `.example.com`. By including the full name you can\n"
"exclude specific host names, so to make `www.example.com` not use a proxy but\n"
"still have `foo.example.com` do it, set `NO_PROXY` to `www.example.com`.\n"
"\n"
"The usage of the `-x`/`--proxy` flag overrides the environment variables.\n"
"\n"
"## Netrc\n"
"\n"
"Unix introduced the `.netrc` concept a long time ago. It is a way for a user\n"
, stdout);
 fputs(
"to specify name and password for commonly visited FTP sites in a file so that\n"
"you do not have to type them in each time you visit those sites. You realize\n"
"this is a big security risk if someone else gets hold of your passwords,\n"
"therefore most Unix programs will not read this file unless it is only readable\n"
"by yourself (curl does not care though).\n"
"\n"
"`--netrc-optional` options). This is not restricted to just FTP, so curl can\n"
"use it for all protocols where authentication is used.\n"
"\n"
, stdout);
 fputs(
"A simple `.netrc` file could look something like:\n"
"    machine curl.se login iamdaniel password mysecret\n"
"\n"
"## Custom Output\n"
"\n"
"To better allow script programmers to get to know about the progress of curl,\n"
"the `-w`/`--write-out` option was introduced. Using this, you can specify what\n"
"information from the previous transfer you want to extract.\n"
"\n"
"To display the amount of bytes downloaded together with some text and an\n"
"ending newline:\n"
"\n"
"    curl -w 'We downloaded %{size_download} bytes\\n' www.example.com\n"
, stdout);
 fputs(
"\n"
"## Kerberos FTP Transfer\n"
"\n"
"kerberos package installed and used at curl build time for it to be available.\n"
"\n"
"First, get the krb-ticket the normal way, like with the `kinit`/`kauth` tool.\n"
"Then use curl in way similar to:\n"
"\n"
"    curl --krb private ftp://krb4site.example.com -u username:fakepwd\n"
"\n"
"There is no use for a password on the `-u` switch, but a blank one will make\n"
"\n"
"## TELNET\n"
"\n"
"The curl telnet support is basic and easy to use. Curl passes all data passed\n"
, stdout);
 fputs(
"to it on stdin to the remote server. Connect to a remote telnet server using a\n"
"command line similar to:\n"
"\n"
"    curl telnet://remote.example.com\n"
"\n"
"And enter the data to pass to the server on stdin. The result will be sent to\n"
"stdout or to the file you specify with `-o`.\n"
"\n"
"You might want the `-N`/`--no-buffer` option to switch off the buffered output\n"
"for slow connections or similar.\n"
"\n"
"Pass options to the telnet protocol negotiation, by using the `-t` option. To\n"
, stdout);
 fputs(
"tell the server we use a vt100 terminal, try something like:\n"
"\n"
"    curl -tTTYPE=vt100 telnet://remote.example.com\n"
"Other interesting options for it `-t` include:\n"
"\n"
" - `XDISPLOC=<X display>` Sets the X display location.\n"
" - `NEW_ENV=<var,val>` Sets an environment variable.\n"
"\n"
"NOTE: The telnet protocol does not specify any way to login with a specified\n"
"user and password so curl cannot do that automatically. To do that, you need to\n"
, stdout);
 fputs(
"track when the login prompt is received and send the username and password\n"
"accordingly.\n"
"\n"
"## Persistent Connections\n"
"\n"
"Specifying multiple files on a single command line will make curl transfer all\n"
"of them, one after the other in the specified order.\n"
"\n"
"libcurl will attempt to use persistent connections for the transfers so that\n"
"the second transfer to the same host can use the same connection that was\n"
"already initiated and was left open in the previous transfer. This greatly\n"
, stdout);
 fputs(
"decreases connection time for all but the first transfer and it makes a far\n"
"better use of the network.\n"
"\n"
"Note that curl cannot use persistent connections for transfers that are used\n"
"in subsequent curl invokes. Try to stuff as many URLs as possible on the same\n"
"command line if they are using the same host, as that will make the transfers\n"
"faster. If you use an HTTP proxy for file transfers, practically all transfers\n"
"will be persistent.\n"
"\n"
"## Multiple Transfers With A Single Command Line\n"
"\n"
, stdout);
 fputs(
"As is mentioned above, you can download multiple files with one command line\n"
"by simply adding more URLs. If you want those to get saved to a local file\n"
"instead of just printed to stdout, you need to add one save option for each\n"
"URL you specify. Note that this also goes for the `-O` option (but not\n"
"`--remote-name-all`).\n"
"\n"
"For example: get two files and use `-O` for the first and a custom file\n"
"name for the second:\n"
"\n"
"    curl -O http://example.com/file.txt ftp://example.com/moo.exe -o moo.jpg\n"
"\n"
, stdout);
 fputs(
"You can also upload multiple files in a similar fashion:\n"
"\n"
"    curl -T local1 ftp://example.com/moo.exe -T local2 ftp://example.com/moo2.txt\n"
"\n"
"## IPv6\n"
"\n"
"address and fall back to IPv4 if the connection fails. The `--ipv4` and\n"
"`--ipv6` options can specify which address to use when both are\n"
"available. IPv6 addresses can also be specified directly in URLs using the\n"
"syntax:\n"
"\n"
"    http://[2001:1890:1112:1::20]/overview.html\n"
"\n"
"When this style is used, the `-g` option must be given to stop curl from\n"
, stdout);
 fputs(
"interpreting the square brackets as special globbing characters. Link local\n"
"and site local addresses including a scope identifier, such as `fe80::1234%1`,\n"
"may also be used, but the scope portion must be numeric or match an existing\n"
"network interface on Linux and the percent character must be URL escaped. The\n"
"previous example in an SFTP URL might look like:\n"
"\n"
"    sftp://[fe80::1234%251]/\n"
"\n"
"IPv6 addresses provided other than in URLs (e.g. to the `--proxy`,\n"
, stdout);
 fputs(
"`--interface` or `--ftp-port` options) should not be URL encoded.\n"
"\n"
"## Mailing Lists\n"
"\n"
"For your convenience, we have several open mailing lists to discuss curl, its\n"
"development and things relevant to this. Get all info at\n"
"https://curl.se/mail/.\n"
"\n"
"Please direct curl questions, feature requests and trouble reports to one of\n"
"these mailing lists instead of mailing any individual.\n"
"\n"
"Available lists include:\n"
"\n"
"### `curl-users`\n"
"\n"
"Users of the command line tool. How to use it, what does not work, new\n"
, stdout);
 fputs(
"features, related tools, questions, news, installations, compilations,\n"
"running, porting etc.\n"
"\n"
"### `curl-library`\n"
"\n"
"Developers using or developing libcurl. Bugs, extensions, improvements.\n"
"\n"
"### `curl-announce`\n"
"\n"
"Low-traffic. Only receives announcements of new public versions. At worst,\n"
"that makes something like one or two mails per month, but usually only one\n"
"mail every second month.\n"
"\n"
"### `curl-and-php`\n"
"\n"
"Using the curl functions in PHP. Everything curl with a PHP angle. Or PHP with\n"
"a curl angle.\n"
"\n"
, stdout);
 fputs(
"### `curl-and-python`\n"
"\n"
"Python hackers using curl with or without the python binding pycurl.\n"
"\n"
, stdout) ;
}
#endif /* USE_MANUAL */
