// this header is auto-generated by CMake

#pragma once

#include "caf/detail/log_level.hpp"

#define CAF_LOG_LEVEL CAF_LOG_LEVEL_QUIET

/// Denotes the version of CAF in the format {MAJOR}{MINOR}{PATCH}, whereas
/// minor and patch versions use two-digit decimal numbers (but without leading
/// zeros), e.g. 900 is version 0.9.0 and 10000 is version 1.0.0.
#define CAF_VERSION 0001

/// Denotes version of CAF as a string in the format "{MAJOR}.{MINOR}.{PATCH}".
#define CAF_VERSION_STR "1.0.1"

/// Defined to the major version number of CAF.
#define CAF_VERSION_MAJOR 1

/// Defined to the minor version number of CAF.
#define CAF_VERSION_MINOR 0

/// Defined to the patch version number of CAF.
#define CAF_VERSION_PATCH 1

/* #undef CAF_ENABLE_RUNTIME_CHECKS */

#define CAF_ENABLE_EXCEPTIONS

/* #undef CAF_ENABLE_ACTOR_PROFILER */

/* #undef CAF_USE_STD_FORMAT */

// Backwards compatibility macros.
#define CAF_MAJOR_VERSION 1
#define CAF_MINOR_VERSION 0
#define CAF_PATCH_VERSION 1
