
also-ignore:
		
	/doc/src/
	/libs/atomic/src/
	/libs/charconv/src/
	/libs/chrono/src/
	/libs/cobalt/src/
	/libs/container/src/
	/libs/context/src/
	/libs/contract/src/
	/libs/coroutine/src/
	/libs/date_time/src/
	/libs/exception/src/
	/libs/fiber/src/
	/libs/filesystem/src/
	/libs/geometry/doc/index/src/
	/libs/geometry/doc/src/
	/libs/geometry/doc/src/docutils/tools/doxygen_xml2qbk/sample/src/
	/libs/graph/src/
	/libs/graph_parallel/src/
	/libs/hof/doc/src/
	/libs/iostreams/src/
	/libs/json/src/
	/libs/locale/src/
	/libs/log/src/
	/libs/math/src/
	/libs/metaparse/tools/benchmark/src/
	/libs/mpi/src/
	/libs/mpl/doc/src/
	/libs/mpl/preprocessed/src/
	/libs/msm/doc/src/
	/libs/mysql/test/common/src/
	/libs/mysql/test/integration/src/
	/libs/mysql/test/unit/src/
	/libs/nowide/src/
	/libs/outcome/doc/src/
	/libs/process/src/
	/libs/program_options/src/
	/libs/python/src/
	/libs/random/src/
	/libs/redis/benchmarks/rust/echo_server_direct/src/
	/libs/redis/benchmarks/rust/echo_server_over_redis/src/
	/libs/regex/src/
	/libs/serialization/src/
	/libs/smart_ptr/extras/src/
	/libs/spirit/example/x3/rexpr/rexpr_full/src/
	/libs/stacktrace/src/
	/libs/system/src/
	/libs/test/src/
	/libs/test/tools/console_test_runner/src/
	/libs/thread/src/
	/libs/timer/src/
	/libs/type_erasure/src/
	/libs/url/src/
	/libs/wave/src/
	/tools/auto_index/src/
	/tools/boostdep/doc/src/
	/tools/boostdep/src/
	/tools/build/doc/src/
	/tools/build/src/
	/tools/build/test/toolset-mock/src/
	/tools/inspect/src/
	/tools/quickbook/src/
	/tools/quickbook/test/src/
			
	/libs/accumulators/example/
	/libs/algorithm/example/
	/libs/algorithm/minmax/example/
	/libs/algorithm/string/example/
	/libs/asio/example/
	/libs/beast/example/
	/libs/bimap/example/
	/libs/callable_traits/example/
	/libs/chrono/example/
	/libs/circular_buffer/example/
	/libs/cobalt/example/
	/libs/compute/example/
	/libs/container/example/
	/libs/context/example/
	/libs/contract/example/
	/libs/convert/example/
	/libs/coroutine/example/
	/libs/coroutine2/example/
	/libs/date_time/example/
	/libs/describe/example/
	/libs/dll/example/
	/libs/dynamic_bitset/example/
	/libs/endian/example/
	/libs/exception/example/
	/libs/filesystem/example/
	/libs/flyweight/example/
	/libs/format/example/
	/libs/function/example/
	/libs/function_types/example/
	/libs/fusion/example/
	/libs/geometry/example/
	/libs/geometry/index/example/
	/libs/gil/example/
	/libs/graph/example/
	/libs/graph_parallel/example/
	/libs/hana/example/
	/libs/hof/example/
	/libs/icl/example/
	/libs/interprocess/example/
	/libs/intrusive/example/
	/libs/iostreams/example/
	/libs/iterator/example/
	/libs/json/example/
	/libs/leaf/example/
	/libs/lexical_cast/example/
	/libs/local_function/example/
	/libs/log/example/
	/libs/math/example/
	/libs/metaparse/example/
	/libs/move/example/
	/libs/mpi/example/
	/libs/mpl/example/
	/libs/msm/example/
	/libs/multiprecision/example/
	/libs/multi_array/example/
	/libs/multi_index/example/
	/libs/mysql/example/
	/libs/outcome/example/
	/libs/pfr/example/
	/libs/phoenix/example/
	/libs/polygon/example/
	/libs/poly_collection/example/
	/libs/pool/example/
	/libs/process/example/
	/libs/program_options/example/
	/libs/property_map/example/
	/libs/proto/example/
	/libs/python/example/
	/libs/random/example/
	/libs/ratio/example/
	/libs/redis/example/
	/libs/regex/example/
	/libs/safe_numerics/example/
	/libs/scope_exit/example/
	/libs/serialization/example/
	/libs/signals2/example/
	/libs/smart_ptr/example/
	/libs/sort/example/
	/libs/spirit/classic/example/
	/libs/spirit/classic/phoenix/example/
	/libs/spirit/example/
	/libs/spirit/repository/example/
	/libs/stacktrace/example/
	/libs/statechart/example/
	/libs/static_assert/example/
	/libs/stl_interfaces/example/
	/libs/test/example/
	/libs/thread/example/
	/libs/timer/example/
	/libs/tokenizer/example/
	/libs/type_erasure/example/
	/libs/units/example/
	/libs/url/example/
	/libs/xpressive/example/
	/libs/yap/example/
	/tools/build/example/
	/tools/docca/example/

	/libs/container_hash/examples/
	/libs/fiber/examples/
	/libs/geometry/doc/src/examples/
	/libs/heap/examples/
	/libs/histogram/examples/
	/libs/locale/examples/
	/libs/lockfree/examples/
	/libs/numeric/interval/examples/
	/libs/numeric/odeint/examples/
	/libs/numeric/ublas/examples/
	/libs/phoenix/doc/examples/
	/libs/property_tree/examples/
	/libs/test/doc/examples/
	/libs/type_index/examples/
	/libs/type_traits/examples/
	/libs/unordered/examples/
	/tools/boostdep/examples/
	/tools/quickbook/examples/

	/bin.v2/tools/
	/libs/asio/tools/
	/libs/beast/tools/
	/libs/config/tools/
	/libs/format/tools/
	/libs/heap/tools/
	/libs/histogram/tools/
	/libs/locale/tools/
	/libs/math/tools/
	/libs/metaparse/tools/
	/libs/mp11/tools/
	/libs/multiprecision/tools/
	/libs/mysql/tools/
	/libs/nowide/tools/
	/libs/predef/tools/
	/libs/redis/tools/
	/libs/regex/tools/
	/libs/static_string/tools/
	/libs/test/tools/
	/libs/type_traits/tools/
	/libs/winapi/tools/
	/libs/xpressive/tools/
	
	/libs/wave/tool/

sources:
    ../../scripts/boost/libboost_tests-dummy.cpp
