
also-ignore:
	/libs/test/test/
	bug/
	example/
	/libs/test/doc/examples/
	/libs/test/doc/snippet/

	/libs/accumulators/
	/libs/algorithm/
	/libs/align/
	/libs/any/
	/libs/array/
	/libs/asio/
	/libs/assert/
	/libs/assign/
	/libs/atomic/
	/libs/beast/
	/libs/bimap/
	/libs/bind/
	/libs/callable_traits/
	/libs/charconv/
	/libs/chrono/
	/libs/circular_buffer/
	/libs/cobalt/
	/libs/compat/
	/libs/compatibility/
	/libs/compute/
	/libs/concept_check/
	/libs/config/
	/libs/container/
	/libs/container_hash/
	/libs/context/
	/libs/contract/
	/libs/conversion/
	/libs/convert/
	/libs/core/
	/libs/coroutine/
	/libs/coroutine2/
	/libs/crc/
	/libs/date_time/
	/libs/describe/
	/libs/detail/
	/libs/dll/
	/libs/dynamic_bitset/
	/libs/endian/
	/libs/exception/
	/libs/fiber/
	/libs/filesystem/
	/libs/flyweight/
	/libs/foreach/
	/libs/format/
	/libs/function/
	/libs/functional/
	/libs/function_types/
	/libs/fusion/
	/libs/geometry/
	/libs/gil/
	/libs/graph/
	/libs/graph_parallel/
	/libs/hana/
	/libs/headers/
	/libs/heap/
	/libs/histogram/
	/libs/hof/
	/libs/icl/
	/libs/integer/
	/libs/interprocess/
	/libs/intrusive/
	/libs/io/
	/libs/iostreams/
	/libs/iterator/
	/libs/json/
	/libs/lambda/
	/libs/lambda2/
	/libs/leaf/
	/libs/lexical_cast/
	/libs/locale/
	/libs/local_function/
	/libs/lockfree/
	/libs/log/
	/libs/logic/
	/libs/math/
	/libs/metaparse/
	/libs/move/
	/libs/mp11/
	/libs/mpi/
	/libs/mpl/
	/libs/msm/
	/libs/multiprecision/
	/libs/multi_array/
	/libs/multi_index/
	/libs/mysql/
	/libs/nowide/
	/libs/numeric/
	/libs/optional/
	/libs/outcome/
	/libs/parameter/
	/libs/parameter_python/
	/libs/pfr/
	/libs/phoenix/
	/libs/polygon/
	/libs/poly_collection/
	/libs/pool/
	/libs/predef/
	/libs/preprocessor/
	/libs/process/
	/libs/program_options/
	/libs/property_map/
	/libs/property_map_parallel/
	/libs/property_tree/
	/libs/proto/
	/libs/ptr_container/
	/libs/python/
	/libs/qvm/
	/libs/random/
	/libs/range/
	/libs/ratio/
	/libs/rational/
	/libs/redis/
	/libs/regex/
	/libs/safe_numerics/
	/libs/scope/
	/libs/scope_exit/
	/libs/serialization/
	/libs/signals2/
	/libs/smart_ptr/
	/libs/sort/
	/libs/spirit/
	/libs/stacktrace/
	/libs/statechart/
	/libs/static_assert/
	/libs/static_string/
	/libs/stl_interfaces/
	/libs/system/
#	/libs/test/
	/libs/thread/
	/libs/throw_exception/
	/libs/timer/
	/libs/tokenizer/
	/libs/tti/
	/libs/tuple/
	/libs/typeof/
	/libs/type_erasure/
	/libs/type_index/
	/libs/type_traits/
	/libs/units/
	/libs/unordered/
	/libs/url/
	/libs/utility/
	/libs/uuid/
	/libs/variant/
	/libs/variant2/
	/libs/vmd/
	/libs/wave/
	/libs/winapi/
	/libs/xpressive/
	/libs/yap/
	
	/tools/
	/boost/
	/doc/
	/more/
	/status/
	/util/
	
sources:
    ../../scripts/boost/libboost-test-dummy.cpp
