
also-ignore:
		
	/doc/src/
	/libs/atomic/src/
	/libs/charconv/src/
	/libs/chrono/src/
	/libs/cobalt/src/
	/libs/container/src/
	/libs/context/src/
	/libs/contract/src/
	/libs/coroutine/src/
	/libs/date_time/src/
	/libs/exception/src/
	/libs/fiber/src/
	/libs/filesystem/src/
	/libs/geometry/doc/index/src/
	/libs/geometry/doc/src/
	/libs/graph/src/
	/libs/graph_parallel/src/
	/libs/hof/doc/src/
	/libs/iostreams/src/
	/libs/json/src/
	/libs/locale/src/
	/libs/log/src/
	/libs/math/src/
	/libs/metaparse/tools/benchmark/src/
	/libs/mpi/src/
	/libs/mpl/doc/src/
	/libs/mpl/preprocessed/src/
	/libs/msm/doc/src/
	/libs/mysql/test/common/src/
	/libs/mysql/test/integration/src/
	/libs/mysql/test/unit/src/
	/libs/nowide/src/
	/libs/outcome/doc/src/
	/libs/process/src/
	/libs/program_options/src/
	/libs/python/src/
	/libs/random/src/
	/libs/redis/benchmarks/rust/echo_server_direct/src/
	/libs/redis/benchmarks/rust/echo_server_over_redis/src/
	/libs/regex/src/
	/libs/serialization/src/
	/libs/smart_ptr/extras/src/
	/libs/stacktrace/src/
	/libs/system/src/
	/libs/test/src/
	/libs/test/tools/console_test_runner/src/
	/libs/thread/src/
	/libs/timer/src/
	/libs/type_erasure/src/
	/libs/url/src/
	/libs/wave/src/
	/tools/auto_index/src/
	/tools/boostdep/doc/src/
	/tools/boostdep/src/
	/tools/build/doc/src/
	/tools/build/src/
	/tools/build/test/toolset-mock/src/
	/tools/inspect/src/
	/tools/quickbook/src/
	/tools/quickbook/test/src/
			
	/libs/accumulators/example/
	/libs/algorithm/example/
	/libs/algorithm/minmax/example/
	/libs/algorithm/string/example/
	/libs/asio/example/
	/libs/beast/example/
	/libs/bimap/example/
	/libs/callable_traits/example/
	/libs/chrono/example/
	/libs/circular_buffer/example/
	/libs/cobalt/example/
	/libs/compute/example/
	/libs/container/example/
	/libs/context/example/
	/libs/contract/example/
	/libs/convert/example/
	/libs/coroutine/example/
	/libs/coroutine2/example/
	/libs/date_time/example/
	/libs/describe/example/
	/libs/dll/example/
	/libs/dynamic_bitset/example/
	/libs/endian/example/
	/libs/exception/example/
	/libs/filesystem/example/
	/libs/flyweight/example/
	/libs/format/example/
	/libs/function/example/
	/libs/function_types/example/
	/libs/fusion/example/
	/libs/geometry/example/
	/libs/geometry/index/example/
	/libs/gil/example/
	/libs/graph/example/
	/libs/graph_parallel/example/
	/libs/hana/example/
	/libs/hof/example/
	/libs/icl/example/
	/libs/interprocess/example/
	/libs/intrusive/example/
	/libs/iostreams/example/
	/libs/iterator/example/
	/libs/json/example/
	/libs/leaf/example/
	/libs/lexical_cast/example/
	/libs/local_function/example/
	/libs/log/example/
	/libs/math/example/
	/libs/metaparse/example/
	/libs/move/example/
	/libs/mpi/example/
	/libs/mpl/example/
	/libs/msm/example/
	/libs/multiprecision/example/
	/libs/multi_array/example/
	/libs/multi_index/example/
	/libs/mysql/example/
	/libs/outcome/example/
	/libs/pfr/example/
	/libs/phoenix/example/
	/libs/polygon/example/
	/libs/poly_collection/example/
	/libs/pool/example/
	/libs/process/example/
	/libs/program_options/example/
	/libs/property_map/example/
	/libs/proto/example/
	/libs/python/example/
	/libs/random/example/
	/libs/ratio/example/
	/libs/redis/example/
	/libs/regex/example/
	/libs/safe_numerics/example/
	/libs/scope_exit/example/
	/libs/serialization/example/
	/libs/signals2/example/
	/libs/smart_ptr/example/
	/libs/sort/example/
	/libs/spirit/classic/example/
	/libs/spirit/classic/phoenix/example/
	/libs/spirit/example/
	/libs/spirit/repository/example/
	/libs/stacktrace/example/
	/libs/statechart/example/
	/libs/static_assert/example/
	/libs/stl_interfaces/example/
	/libs/test/example/
	/libs/thread/example/
	/libs/timer/example/
	/libs/tokenizer/example/
	/libs/type_erasure/example/
	/libs/units/example/
	/libs/url/example/
	/libs/xpressive/example/
	/libs/yap/example/
	/tools/build/example/
	/tools/docca/example/

	/libs/container_hash/examples/
	/libs/fiber/examples/
	/libs/geometry/doc/src/examples/
	/libs/heap/examples/
	/libs/histogram/examples/
	/libs/locale/examples/
	/libs/lockfree/examples/
	/libs/numeric/interval/examples/
	/libs/numeric/odeint/examples/
	/libs/numeric/ublas/examples/
	/libs/phoenix/doc/examples/
	/libs/property_tree/examples/
	/libs/test/doc/examples/
	/libs/type_index/examples/
	/libs/type_traits/examples/
	/libs/unordered/examples/
	/tools/boostdep/examples/
	/tools/quickbook/examples/
			
	/doc/test/
	/libs/accumulators/test/
	/libs/algorithm/minmax/test/
	/libs/algorithm/string/test/
	/libs/algorithm/test/
	/libs/align/test/
	/libs/any/test/
	/libs/array/test/
	/libs/asio/test/
	/libs/assert/test/
	/libs/assign/test/
	/libs/atomic/test/
	/libs/beast/test/
	/libs/bimap/test/
	/libs/bind/test/
	/libs/callable_traits/test/
	/libs/charconv/test/
	/libs/chrono/test/
	/libs/circular_buffer/test/
	/libs/cobalt/test/
	/libs/compat/test/
	/libs/compute/test/
	/libs/concept_check/test/
	/libs/config/test/
	/libs/container/test/
	/libs/container_hash/test/
	/libs/context/test/
	/libs/contract/test/
	/libs/conversion/test/
	/libs/convert/test/
	/libs/core/test/
	/libs/coroutine/test/
	/libs/coroutine2/test/
	/libs/crc/test/
	/libs/date_time/test/
	/libs/describe/test/
	/libs/detail/test/
	/libs/dll/test/
	/libs/dynamic_bitset/test/
	/libs/endian/test/
	/libs/exception/test/
	/libs/fiber/test/
	/libs/filesystem/test/
	/libs/flyweight/test/
	/libs/foreach/test/
	/libs/format/test/
	/libs/function/test/
	/libs/functional/factory/test/
	/libs/functional/forward/test/
	/libs/functional/overloaded_function/test/
	/libs/functional/test/
	/libs/function_types/test/
	/libs/fusion/test/
	/libs/geometry/index/test/
	/libs/geometry/test/
	/libs/gil/test/
	/libs/graph/test/
	/libs/graph_parallel/test/
	/libs/hana/test/
	/libs/heap/test/
	/libs/histogram/test/
	/libs/hof/test/
	/libs/icl/test/
	/libs/integer/test/
	/libs/interprocess/test/
	/libs/intrusive/test/
	/libs/io/test/
	/libs/iostreams/test/
	/libs/iterator/test/
	/libs/json/test/
	/libs/lambda/test/
	/libs/lambda2/test/
	/libs/leaf/test/
	/libs/lexical_cast/test/
	/libs/locale/test/
	/libs/local_function/test/
	/libs/lockfree/test/
	/libs/log/test/
	/libs/logic/test/
	/libs/math/test/
	/libs/metaparse/test/
	/libs/move/test/
	/libs/mp11/test/
	/libs/mpi/test/
	/libs/mpl/test/
	/libs/msm/test/
	/libs/multiprecision/test/
	/libs/multi_array/test/
	/libs/multi_index/test/
	/libs/mysql/test/
	/libs/nowide/test/
	/libs/numeric/conversion/test/
	/libs/numeric/interval/test/
	/libs/numeric/odeint/test/
	/libs/numeric/ublas/test/
	/libs/optional/test/
	/libs/outcome/test/
	/libs/parameter/test/
	/libs/parameter_python/test/
	/libs/pfr/test/
	/libs/phoenix/test/
	/libs/polygon/test/
	/libs/poly_collection/test/
	/libs/pool/test/
	/libs/predef/test/
	/libs/preprocessor/test/
	/libs/process/test/
	/libs/program_options/test/
	/libs/property_map/test/
	/libs/property_tree/test/
	/libs/proto/test/
	/libs/ptr_container/test/
	/libs/python/test/
	/libs/qvm/test/
	/libs/random/test/
	/libs/range/test/
	/libs/ratio/test/
	/libs/rational/test/
	/libs/redis/test/
	/libs/regex/test/
	/libs/safe_numerics/test/
	/libs/scope/test/
	/libs/scope_exit/test/
	/libs/serialization/test/
	/libs/signals2/test/
	/libs/smart_ptr/extras/test/
	/libs/smart_ptr/test/
	/libs/sort/test/
	/libs/spirit/test/
	/libs/stacktrace/test/
	/libs/statechart/test/
	/libs/static_assert/test/
	/libs/static_string/test/
	/libs/stl_interfaces/test/
	/libs/system/test/
	/libs/test/
	/libs/thread/test/
	/libs/throw_exception/test/
	/libs/timer/test/
	/libs/tokenizer/test/
	/libs/tti/test/
	/libs/tuple/test/
	/libs/typeof/test/
	/libs/type_erasure/test/
	/libs/type_index/test/
	/libs/type_traits/test/
	/libs/units/test/
	/libs/unordered/test/
	/libs/url/test/
	/libs/utility/test/
	/libs/uuid/test/
	/libs/variant/test/
	/libs/variant2/test/
	/libs/vmd/test/
	/libs/wave/test/
	/libs/winapi/test/
	/libs/xpressive/test/
	/libs/yap/test/
	/tools/auto_index/test/
	/tools/bcp/test/
	/tools/boostbook/test/
	/tools/boostdep/test/
	/tools/boost_install/test/
	/tools/build/test/
	/tools/check_build/test/
	/tools/cmake/test/
	/tools/docca/test/
	/tools/quickbook/test/

sources:
    ../../scripts/boost/libboost_tools-dummy.cpp
