
also-ignore:
	/Examples/Android
	/Examples/Emscripten
	/Examples/GUI/Cocoa
	/Examples/GUI/QML
	/Examples/GUI/Qt
	/Examples/iOS
	/Filters/Python
	/ThirdParty/cli11/vtkcli11
	/ThirdParty/eigen/vtkeigen
	/ThirdParty/expat/vtkexpat
	/ThirdParty/exprtk/vtkexprtk
	/ThirdParty/fast_float/vtkfast_float
	/ThirdParty/fmt/vtkfmt
	/ThirdParty/freetype/vtkfreetype
	/ThirdParty/hdf5/vtkhdf5
	/ThirdParty/jpeg/vtkjpeg
	/ThirdParty/jsoncpp/vtkjsoncpp
	/ThirdParty/kissfft/vtkkissfft
	/ThirdParty/libharu/vtklibharu
	/ThirdParty/libproj/vtklibproj
	/ThirdParty/libxml2/vtklibxml2
	/ThirdParty/loguru/vtkloguru
	/ThirdParty/lz4/vtklz4
	/ThirdParty/lzma/vtklzma
	/ThirdParty/mpi4py
	/ThirdParty/netcdf/vtknetcdf
	/ThirdParty/nlohmannjson/vtknlohmannjson
	/ThirdParty/ogg/vtkogg
	/ThirdParty/pegtl/vtkpegtl
	/ThirdParty/png/vtkpng
	/ThirdParty/pugixml/vtkpugixml
	/ThirdParty/scn/vtkscn
	/ThirdParty/sqlite/vtksqlite
	/ThirdParty/theora/vtktheora
	/ThirdParty/tiff/vtktiff
	/ThirdParty/token/vtktoken
	/ThirdParty/utf8/vtkutf8
	/ThirdParty/verdict/vtkverdict
	/ThirdParty/zlib/vtkzlib
	/Views/Qt
	/Web/Python
	/Web/WebAssembly
	/Wrapping/Java
	/Wrapping/Python
	/Wrapping/PythonCore
